In [ ]:
# Numpy arrays are more efficient that Python lists in terms of memory consumption and speed
import numpy as np

# create a numpy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.ndim) # number of dimensions

[1 2 3 4 5]
1


In [ ]:
# create a 3D numpy array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# iterate through the 3D numpy array
for i in range(arr_3d.shape[0]): # shape is a tuple that contains the dimensions of the array
    for j in range(arr_3d.shape[1]): # shape[0] is the number of rows, shape[1] is the number of columns
        for k in range(arr_3d.shape[2]): # shape[2] is the number of layers
            print(arr_3d[i, j, k])

1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
# Example 1: Matrix multiplication of 2D arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
result_2d = np.matmul(A, B)
print("Matrix multiplication of 2D arrays:\n", result_2d)

# Example 2: Matrix multiplication of 1D and 2D arrays
C = np.array([1, 2])
D = np.array([[3, 4], [5, 6]])

# Perform matrix multiplication
result_1d_2d = np.matmul(C, D)
print("Matrix multiplication of 1D and 2D arrays:\n", result_1d_2d)

# Example 3: Matrix multiplication of 3D arrays
E = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
F = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

# Perform matrix multiplication
result_3d = np.matmul(E, F)
print("Matrix multiplication of 3D arrays:\n", result_3d)

Matrix multiplication of 2D arrays:
 [[19 22]
 [43 50]]
Matrix multiplication of 1D and 2D arrays:
 [13 16]
Matrix multiplication of 3D arrays:
 [[[ 31  34]
  [ 71  78]]

 [[155 166]
  [211 226]]]


In [13]:
# Median-based anomaly detection
import pandas as pd
import numpy as np
x = pd.Series([2.1, 2.3, 4.5, 2.2, 2.4, 5,78])
threshold = 2.0 
median = np.median(x)
outliers = []
for i in range(len(x)):
    if abs(x[i] - median) > threshold:
        outliers.append(x[i])
    print(outliers)

[]
[]
[4.5]
[4.5]
[4.5]
[4.5, 5.0]
[4.5, 5.0, 78.0]


In [15]:
# Mean-based anomaly detection
mean = np. mean(x)
std = np.std(x)
outliers = []
for i in x:
    if (i < mean - std) or (i > mean + std):
        outliers.append(i)
    print(outliers)



[]
[]
[]
[]
[]
[]
[78.0]


In [16]:
# z-score based anomaly detection
for item in x:
    z_score = (item - mean) / std
    if z_score > 1.5:
        outliers.append(item)
    print(outliers)

[78.0]
[78.0]
[78.0]
[78.0]
[78.0]
[78.0]
[78.0, 78.0]


In [17]:
# Interquartile range (IQR) based anomaly detection
Q1, Q3 = np.percentile(x, [25, 75])
IQR = Q3 - Q1
outliers = []
for item in x:
    if (item < Q1 - 1.5 * IQR) or (item > Q3 + 1.5 * IQR):
        outliers.append(item)
    print(outliers)


[]
[]
[]
[]
[]
[]
[78.0]


In [19]:
import re

# Sample text
text = "The rain in Spain stays mainly in the plain."

# 1. Find all occurrences of a pattern
pattern = r'\b\w*ain\b'
matches = re.findall(pattern, text)
print("Matches:", matches)

# 2. Search for the first occurrence of a pattern
match = re.search(pattern, text)
if match:
    print("First match:", match.group())

# 3. Replace all occurrences of a pattern
replaced_text = re.sub(pattern, 'XYZ', text)
print("Replaced text:", replaced_text)

# 4. Split text by a pattern
split_text = re.split(r'\s+', text)
print("Split text:", split_text)

# 5. Compile a regular expression for repeated use
compiled_pattern = re.compile(pattern)
matches = compiled_pattern.findall(text)
print("Matches with compiled pattern:", matches)

Matches: ['rain', 'Spain', 'plain']
First match: rain
Replaced text: The XYZ in XYZ stays mainly in the XYZ.
Split text: ['The', 'rain', 'in', 'Spain', 'stays', 'mainly', 'in', 'the', 'plain.']
Matches with compiled pattern: ['rain', 'Spain', 'plain']


In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, MaxAbsScaler
import pandas as pd

# Sample data
data = {'Feature1': [10, 20, 30, 40, 50],
    'Feature2': [100, 200, 300, 400, 500]}
df = pd.DataFrame(data)

# Min-Max Scaling ==> normalization
# Goal: Scale data to a fixed range [0, 1].
# Min-Max scaling is recommended when the data does not follow a normal distribution.
min_max_scaler = MinMaxScaler()
df_min_max_scaled = pd.DataFrame(min_max_scaler.fit_transform(df), columns=df.columns)
print("Min-Max Scaled Data:\n", df_min_max_scaled)

# Standardization
# Goal: Scale data to have a mean of 0 and a standard deviation of 1.
# Standardization is recommended when the data follows a normal distribution.

standard_scaler = StandardScaler()
df_standard_scaled = pd.DataFrame(standard_scaler.fit_transform(df), columns=df.columns)
print("Standard Scaled Data:\n", df_standard_scaled)

# Robust Scaling
# Goal: Scale data based on the IQR (Interquartile Range).
# Robust scaling is recommended when the data contains outliers.
robust_scaler = RobustScaler()
df_robust_scaled = pd.DataFrame(robust_scaler.fit_transform(df), columns=df.columns)
print("Robust Scaled Data:\n", df_robust_scaled)

# MaxAbs Scaling
# Goal: Scale data based on the maximum absolute value
# MaxAbs scaling is recommended when the data contains both positive and negative values.
max_abs_scaler = MaxAbsScaler()
df_max_abs_scaled = pd.DataFrame(max_abs_scaler.fit_transform(df), columns=df.columns)
print("MaxAbs Scaled Data:\n", df_max_abs_scaled)

Min-Max Scaled Data:
    Feature1  Feature2
0      0.00      0.00
1      0.25      0.25
2      0.50      0.50
3      0.75      0.75
4      1.00      1.00
Standard Scaled Data:
    Feature1  Feature2
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214
Robust Scaled Data:
    Feature1  Feature2
0      -1.0      -1.0
1      -0.5      -0.5
2       0.0       0.0
3       0.5       0.5
4       1.0       1.0
MaxAbs Scaled Data:
    Feature1  Feature2
0       0.2       0.2
1       0.4       0.4
2       0.6       0.6
3       0.8       0.8
4       1.0       1.0
