In [1]:
# Data serialization
import json  
data = {'name': 'Sam', 'age': 34}
json_str = json.dumps(data)
print(json_str)

parsed_data = json.loads(json_str)
print(parsed_data)
print(type(parsed_data))


{"name": "Sam", "age": 34}
{'name': 'Sam', 'age': 34}
<class 'dict'>


In [2]:
# csv
import csv
with open('example.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['name', 'age'])
    writer.writerow(['Sam', 43])

# read
with open('example.csv', mode='r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['name', 'age']
['Sam', '43']


In [3]:
# datetime
from datetime import datetime, timedelta
now = datetime.now()
print(now)

yesterday = now - timedelta(days=1)
print(yesterday)

2025-05-19 19:22:08.414953
2025-05-18 19:22:08.414953


In [4]:
# time
import time

print(time.time())
time.sleep(2)
print(time.time())

1747671728.4340484
1747671730.437085


In [5]:
# regular expressions
import re

pattern = r'\d+' # d -> digits
text = 'There are 123 apples'
match = re.search(pattern, text)
print(match.group())

123


In [6]:
# file operations
# Read a file
with open('iris.csv', mode='r') as file:
    content = file.read()
    print(content)

"sepal.length","sepal.width","petal.length","petal.width","variety"
5.1,3.5,1.4,.2,"Setosa"
4.9,3,1.4,.2,"Setosa"
4.7,3.2,1.3,.2,"Setosa"
4.6,3.1,1.5,.2,"Setosa"
5,3.6,1.4,.2,"Setosa"
5.4,3.9,1.7,.4,"Setosa"
4.6,3.4,1.4,.3,"Setosa"
5,3.4,1.5,.2,"Setosa"
4.4,2.9,1.4,.2,"Setosa"
4.9,3.1,1.5,.1,"Setosa"
5.4,3.7,1.5,.2,"Setosa"
4.8,3.4,1.6,.2,"Setosa"
4.8,3,1.4,.1,"Setosa"
4.3,3,1.1,.1,"Setosa"
5.8,4,1.2,.2,"Setosa"
5.7,4.4,1.5,.4,"Setosa"
5.4,3.9,1.3,.4,"Setosa"
5.1,3.5,1.4,.3,"Setosa"
5.7,3.8,1.7,.3,"Setosa"
5.1,3.8,1.5,.3,"Setosa"
5.4,3.4,1.7,.2,"Setosa"
5.1,3.7,1.5,.4,"Setosa"
4.6,3.6,1,.2,"Setosa"
5.1,3.3,1.7,.5,"Setosa"
4.8,3.4,1.9,.2,"Setosa"
5,3,1.6,.2,"Setosa"
5,3.4,1.6,.4,"Setosa"
5.2,3.5,1.5,.2,"Setosa"
5.2,3.4,1.4,.2,"Setosa"
4.7,3.2,1.6,.2,"Setosa"
4.8,3.1,1.6,.2,"Setosa"
5.4,3.4,1.5,.4,"Setosa"
5.2,4.1,1.5,.1,"Setosa"
5.5,4.2,1.4,.2,"Setosa"
4.9,3.1,1.5,.2,"Setosa"
5,3.2,1.2,.2,"Setosa"
5.5,3.5,1.3,.2,"Setosa"
4.9,3.6,1.4,.1,"Setosa"
4.4,3,1.3,.2,"Setosa"
5.1,3.4,1.5,.2,"Seto

In [7]:
# read line by line
with open('example.csv', 'r') as file:
    for line in file:
        print(line.strip())

name,age
Sam,43


In [8]:
# writing a file
with open('example.txt', 'a') as file: # a -> append, w -> write, w+ -> read and write
    file.write('This is my new file')
    file.write('Hello world')

# writing a list of lines to a file
lines=['First line\n', 'Second line\n', 'Third line \n']
with open('example.txt', 'a') as file:
    file.writelines(lines)

In [9]:
# Binary files
# writing to a binary file
data = b'\x00\x01\x02\x03\x04'
with open('example.bin', 'wb') as file:
    file.write(data)

In [10]:
# read binary file
with open('example.bin', 'rb') as file:
    content = file.read()
    print(content)

b'\x00\x01\x02\x03\x04'


In [11]:
with open('example.txt', 'r') as source_file:
    content = source_file.read()

with open('destination.txt', 'w') as destination_file:
    destination_file.write(content)

In [12]:
# read a text fiel and count the nuber of lines, words and characters
def count_text_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
        line_count = len(lines)
        word_count = sum(len(line.split()) for line in lines)
        char_count = sum(len(line) for line in lines)
    return line_count, word_count, char_count

file_path = 'example.txt'
lines, words, characters = count_text_file(file_path)
print(f'lines: {lines}, words: {words}, characters: {characters}')

lines: 12, words: 54, characters: 320


In [ ]:
# writing then reading the fiel
with open('example2.txt', 'w+') as file:
    file.write('I love UK\n')
    file.write('Also Illinois\n')

    # move the file cursor to the beginning
    file.seek(0)
    content = file.read()
    print(content)

I love Singapore
Also Illinois



In [14]:
# create new directory
import os
new_directory = "package"
os.mkdir(new_directory)
print(f"Directory {new_directory} is created")

FileExistsError: [Errno 17] File exists: 'package'

In [ ]:
# listing Files and directories
items = os.listdir('.')
print(items)

['python.ipynb', 'destination.txt', 'example.bin', 'example.txt', 'Recommeder_system.ipynb', 'Data', 'package', 'ETH_1h.csv', 'example2.txt', 'iris.csv', 'notebook.ipynb', 'logistic_regression.ipynb', 'classification.ipynb', 'clustering.ipynb', 'decision_tree.ipynb', 'example.csv', 'titanic.csv']


In [ ]:
# Joining paths
dir_name = "new_folder"
file_name = "file.txt"
full_path = os.path.join(os.getcwd(),dir_name, file_name)
print(full_path)

/home/wanyua/Dev/ML/Python-Machine-Learning-Tutorial/Python_for_data_science/new_folder/file.txt


In [ ]:
path = 'example3.txt'
if os.path.exists(path):
    print(f"The path {path} exists")
else:
    print(f"The path {path} does not exist")

The path example3.txt does not exist


In [ ]:
# Checking if a path is file or directory
import os
path = 'example.txt'
if os.path.isfile(path):
    print(f"The path {path} is a file")
elif os.path.isdir(path):
    print(f"The path {path} is a directory")
else:
    print(f"The path {path} is neither a file nor a directory")


The path example.txt is a file


In [ ]:
# getting the absolute path
relative_path = 'example.bin'
absolute_path = os.path.abspath(relative_path)
print(absolute_path)

/home/wanyua/Dev/ML/Python-Machine-Learning-Tutorial/Python_for_data_science/example.bin


In [ ]:
# exceptions handling
try:
    file= open('example.bin', 'r')
    content = file.read()
    print(content)
except FileNotFoundError:
    print("The file does not exist")
except Exception as ex:
    print(ex)
finally:
    if 'file' in locals() and not file.closed:
        file.close()
        print('File closed')


File closed


In [ ]:
!pip install numpy
import numpy as np
arr = np.array([[1,2,3], [3,4,5], [5,4,6]])
print(arr)


  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[[1 2 3]
 [3 4 5]
 [5 4 6]]


In [ ]:
arr[:1]

array([[1, 2, 3]])

In [ ]:
arr[:,2]

array([3, 5, 6])

In [ ]:
arr[0:2, 1:]

array([[2, 3],
       [4, 5]])

In [ ]:
# standardization and normalization
data = np.array([1,2,3,4,5,6,7,8])
print(data[(data > 4) & (data<7)])
# mean and standard deviation 
# standard deviation -> tells you how much the values vary from the average
mean = np.mean(data)
standard_deviation = np.std(data) # standardization -> mean = 0, standardard deviation = 1
print(f"Mean: {mean}, Standard deviation : {standard_deviation}")


# normalize the data -> rescales values so they lie between 0 and 1
norm_data = (data - mean)/ standard_deviation
print(f"Normalized data: {norm_data}")


[5 6]
Mean: 4.5, Standard deviation : 2.29128784747792
Normalized data: [-1.52752523 -1.09108945 -0.65465367 -0.21821789  0.21821789  0.65465367
  1.09108945  1.52752523]


In [ ]:
# pandas -dataframes and series
!pip install pandas
import pandas as pd

  Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
     |████████████████████████████████| 509 kB 365 kB/s eta 0:00:01
     |████████████████████████████████| 347 kB 144 kB/s eta 0:00:01


In [ ]:
# series - one dimension array like object. Similar like a column in a table
data = [1,2,3,4,5]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# creating a series from a dictionary
data = {'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data)
series_dict

a    1
b    2
c    3
dtype: int64

In [ ]:
arr = [1,2,3,4.3,5.3]
print(arr[-3:])
ind = ['a', 'b', 'c', 'd', 'e']
pd.Series(data, index = ind)

[3, 4.3, 5.3]


a    {'name': 'Sam', 'age': 25, 'city': 'new jersey'}
b    {'name': 'Sam', 'age': 25, 'city': 'new jersey'}
c    {'name': 'Sam', 'age': 25, 'city': 'new jersey'}
d    {'name': 'Sam', 'age': 25, 'city': 'new jersey'}
e    {'name': 'Sam', 'age': 25, 'city': 'new jersey'}
dtype: object

In [ ]:
# Data frame - similar to a table or a multidimensional array
# creating a df from a dictionary
data = {
    'Name': ['Sam', 'Vule', 'Chels', 'Ros'],
    'Age': [23,23,45,43],
    'City': ["New Mexico", 'Nairobi', "Pretoria", "Cairo"]
}

print(pd.DataFrame(data))
print(np.array(pd.DataFrame(data)))

    Name  Age        City
0    Sam   23  New Mexico
1   Vule   23     Nairobi
2  Chels   45    Pretoria
3    Ros   43       Cairo
[['Sam' 23 'New Mexico']
 ['Vule' 23 'Nairobi']
 ['Chels' 45 'Pretoria']
 ['Ros' 43 'Cairo']]


In [ ]:
# creating a df from a list of dictionary
data = [
    {'name': 'Sam', 'age': 25, 'city': 'new jersey'},
    {'name': 'Sam', 'age': 25, 'city': 'new jersey'},
    {'name': 'Sam', 'age': 25, 'city': 'new jersey'},
    {'name': 'Sam', 'age': 25, 'city': 'new jersey'},
    {'name': 'Sam', 'age': 25, 'city': 'new jersey'},
]

print(pd.DataFrame(data))

  name  age        city
0  Sam   25  new jersey
1  Sam   25  new jersey
2  Sam   25  new jersey
3  Sam   25  new jersey
4  Sam   25  new jersey


In [ ]:
!pip install kagglehub
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ivankmk/thousand-ml-jobs-in-usa")

print("Path to dataset files:", path)

     |████████████████████████████████| 78 kB 412 kB/s eta 0:00:01
     |████████████████████████████████| 64 kB 304 kB/s eta 0:00:01
     |████████████████████████████████| 147 kB 262 kB/s eta 0:00:01
     |████████████████████████████████| 70 kB 157 kB/s eta 0:00:01
     |████████████████████████████████| 126 kB 147 kB/s eta 0:00:01
     |████████████████████████████████| 159 kB 202 kB/s eta 0:00:01


/home/wanyua/Dev/ML/Python-Machine-Learning-Tutorial/env/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|██████████| 1.60M/1.60M [00:02<00:00, 794kB/s]

Extracting model files...
Path to dataset files: /home/wanyua/.cache/kagglehub/datasets/ivankmk/thousand-ml-jobs-in-usa/versions/1


In [ ]:
df = pd.read_csv('1000_ml_jobs_us.csv')
df.head()

Unnamed: 0 job_posted_date company_address_locality company_address_region  \
0           0      2024-10-31             Indianapolis                Indiana   
1           1      2025-03-14            San Francisco             California   
2           2      2025-04-09                 San Jose                     CA   
3           3      2025-03-22            Mountain View             California   
4           4      2025-03-28                   Boston          Massachusetts   

  company_name             company_website  \
0   Upper Hand       https://upperhand.com   
1       Ikigai   https://www.ikigailabs.io   
2        Adobe        http://www.adobe.com   
3        Waymo  https://waymo.com/careers/   
4          HMH        http://www.hmhco.com   

                                 company_description  \
0  Upper Hand is the leading provider of full-sui...   
1  Built upon years of MIT research, Ikigai is a ...   
2  Adobe is the global leader in digital media an...   
3  On the journey to be the world's most trusted ...   
4  We are an adaptive learning company that empow...   

                                job_description_text   seniority_level  \
0  OverviewUpper Hand is embarking on an exciting...        Internship   
1  Company DescriptionThe Ikigai platform unlocks...  Mid-Senior level   
2  Our CompanyChanging the world through digital ...       Entry level   
3  Waymo is an autonomous driving technology comp...       Entry level   
4  Job Title: Machine Learning EngineerLocation: ...  Mid-Senior level   

                                           job_title  
0  Internship - Machine Learning Engineer & Data ...  
1                          Machine Learning Engineer  
2                          Machine Learning Engineer  
3                Machine Learning Engineer, Training  
4                          Machine Learning Engineer

In [ ]:
df.loc[2] # this is a row

Unnamed: 0                                                                  2
job_posted_date                                                    2025-04-09
company_address_locality                                             San Jose
company_address_region                                                     CA
company_name                                                            Adobe
company_website                                          http://www.adobe.com
company_description         Adobe is the global leader in digital media an...
job_description_text        Our CompanyChanging the world through digital ...
seniority_level                                                   Entry level
job_title                                           Machine Learning Engineer
Name: 2, dtype: object

In [ ]:
df.iloc[0:,3] # column 3

0            Indiana
1         California
2                 CA
3         California
4      Massachusetts
           ...      
992               CA
993            Texas
994               NY
995               CA
996    Massachusetts
Name: company_address_region, Length: 997, dtype: object

In [ ]:
# remove a column
df.drop('Unnamed: 0', axis=1, inplace = True)
df.columns

Index(['job_posted_date', 'company_address_locality', 'company_address_region',
       'company_name', 'company_website', 'company_description',
       'job_description_text', 'seniority_level', 'job_title'],
      dtype='object')

In [ ]:
# drop a row
df.drop(1, inplace= True)
df

job_posted_date company_address_locality company_address_region  \
2        2025-04-09                 San Jose                     CA   
3        2025-03-22            Mountain View             California   
4        2025-03-28                   Boston          Massachusetts   
5        2025-04-02                 San Jose                     CA   
6        2025-03-25                Deerfield                     IL   
..              ...                      ...                    ...   
992      2025-04-03               Menlo Park                     CA   
993      2025-04-01                  Houston                  Texas   
994      2025-04-02                 New York                     NY   
995      2025-04-01            Mountain View                     CA   
996      2025-02-03                Watertown          Massachusetts   

                company_name                  company_website  \
2                      Adobe             http://www.adobe.com   
3                      Waymo       https://waymo.com/careers/   
4                        HMH             http://www.hmhco.com   
5                      Adobe             http://www.adobe.com   
6                  Walgreens         http://www.walgreens.com   
..                       ...                              ...   
992                     Meta     https://www.metacareers.com/   
993       The Lab Consulting  http://www.thelabconsulting.com   
994                  FanDuel     https://www.fanduel.careers/   
995  X, The Moonshot Factory                https://x.company   
996       Tutor Intelligence   https://tutorintelligence.com/   

                                   company_description  \
2    Adobe is the global leader in digital media an...   
3    On the journey to be the world's most trusted ...   
4    We are an adaptive learning company that empow...   
5    Adobe is the global leader in digital media an...   
6    Walgreens (www.walgreens.com) is included in t...   
..                                                 ...   
992  Meta's mission is to build the future of human...   
993  The Lab is a management consulting firm that h...   
994  FanDuel Group is an innovative sports-tech ent...   
995  We create breakthrough technologies to help so...   
996  Tutor Intelligence is a full-service robotics ...   

                                  job_description_text   seniority_level  \
2    Our CompanyChanging the world through digital ...       Entry level   
3    Waymo is an autonomous driving technology comp...       Entry level   
4    Job Title: Machine Learning EngineerLocation: ...  Mid-Senior level   
5    Our CompanyChanging the world through digital ...        Internship   
6    Job SummaryApplies advanced data analysis tool...    Not Applicable   
..                                                 ...               ...   
992  Reality Labs at Meta is building products that...    Not Applicable   
993  We are a mid-sized Management Consulting, Auto...  Mid-Senior level   
994  About FanduelFanDuel Group is the premier mobi...          Director   
995  About The TeamTapestry, is X’s moonshot for th...  Mid-Senior level   
996  The Company:Tutor Intelligence is a startup bu...    Not Applicable   

                                             job_title  
2                            Machine Learning Engineer  
3                  Machine Learning Engineer, Training  
4                            Machine Learning Engineer  
5        2025 Intern - Machine Learning Engineer AI/ML  
6    Data Scientist - Healthcare & Clinical Data (R...  
..                                                 ...  
992  Software Engineer, Computer Vision - Reality Labs  
993                                     Data Scientist  
994                          Software Engineer - React  
995                Machine Learning Engineer, Tapestry  
996                 Robotics Machine Learning Engineer  

[995 rows x 9 columns]

In [ ]:
df.dtypes

job_posted_date             object
company_address_locality    object
company_address_region      object
company_name                object
company_website             object
company_description         object
job_description_text        object
seniority_level             object
job_title                   object
dtype: object

In [ ]:
df.describe()

job_posted_date company_address_locality company_address_region  \
count              995                      948                    882   
unique             116                      178                     87   
top         2025-04-09            San Francisco             California   
freq                87                      147                    307   

       company_name                       company_website  \
count           995                                   981   
unique          486                                   476   
top          TikTok  https://www.tiktok.com/about?lang=en   
freq             88                                    88   

                                      company_description  \
count                                                 983   
unique                                                478   
top     TikTok is the world's leading destination for ...   
freq                                                   88   

                                     job_description_text   seniority_level  \
count                                                 994               986   
unique                                                793                 7   
top     Meta is embarking on the most transformative c...  Mid-Senior level   
freq                                                   12               370   

                        job_title  
count                         995  
unique                        449  
top     Machine Learning Engineer  
freq                          242

In [ ]:
df.isnull().sum()

job_posted_date               0
company_address_locality     47
company_address_region      113
company_name                  0
company_website              14
company_description          12
job_description_text          1
seniority_level               9
job_title                     0
dtype: int64

In [ ]:
df.dropna(subset=['job_description_text'], inplace=True) # for a specific column
df.isnull().sum()

job_posted_date               0
company_address_locality     47
company_address_region      113
company_name                  0
company_website              14
company_description          12
job_description_text          0
seniority_level               8
job_title                     0
dtype: int64

In [ ]:
df.dtypes

job_posted_date             object
company_address_locality    object
company_address_region      object
company_name                object
company_website             object
company_description         object
job_description_text        object
seniority_level             object
job_title                   object
dtype: object

In [ ]:
df.columns

Index(['job_posted_date', 'company_address_locality', 'company_address_region',
       'company_name', 'company_website', 'company_description',
       'job_description_text', 'seniority_level', 'job_title'],
      dtype='object')

In [ ]:
# renaming columns
df = df.rename(columns={'company_address_locality' : 'company_location'})
df.head()

job_posted_date company_location company_address_region company_name  \
2      2025-04-09         San Jose                     CA        Adobe   
3      2025-03-22    Mountain View             California        Waymo   
4      2025-03-28           Boston          Massachusetts          HMH   
5      2025-04-02         San Jose                     CA        Adobe   
6      2025-03-25        Deerfield                     IL    Walgreens   

              company_website  \
2        http://www.adobe.com   
3  https://waymo.com/careers/   
4        http://www.hmhco.com   
5        http://www.adobe.com   
6    http://www.walgreens.com   

                                 company_description  \
2  Adobe is the global leader in digital media an...   
3  On the journey to be the world's most trusted ...   
4  We are an adaptive learning company that empow...   
5  Adobe is the global leader in digital media an...   
6  Walgreens (www.walgreens.com) is included in t...   

                                job_description_text   seniority_level  \
2  Our CompanyChanging the world through digital ...       Entry level   
3  Waymo is an autonomous driving technology comp...       Entry level   
4  Job Title: Machine Learning EngineerLocation: ...  Mid-Senior level   
5  Our CompanyChanging the world through digital ...        Internship   
6  Job SummaryApplies advanced data analysis tool...    Not Applicable   

                                           job_title  
2                          Machine Learning Engineer  
3                Machine Learning Engineer, Training  
4                          Machine Learning Engineer  
5      2025 Intern - Machine Learning Engineer AI/ML  
6  Data Scientist - Healthcare & Clinical Data (R...

In [2]:
# changing data types
df.dtypes
# df['new_column'] = df['column'].astype(float)

NameError: name 'df' is not defined

In [5]:
import pandas as pd
df = pd.read_csv('1000_ml_jobs_us.csv')
df.head()

Unnamed: 0 job_posted_date company_address_locality company_address_region  \
0           0      2024-10-31             Indianapolis                Indiana   
1           1      2025-03-14            San Francisco             California   
2           2      2025-04-09                 San Jose                     CA   
3           3      2025-03-22            Mountain View             California   
4           4      2025-03-28                   Boston          Massachusetts   

  company_name             company_website  \
0   Upper Hand       https://upperhand.com   
1       Ikigai   https://www.ikigailabs.io   
2        Adobe        http://www.adobe.com   
3        Waymo  https://waymo.com/careers/   
4          HMH        http://www.hmhco.com   

                                 company_description  \
0  Upper Hand is the leading provider of full-sui...   
1  Built upon years of MIT research, Ikigai is a ...   
2  Adobe is the global leader in digital media an...   
3  On the journey to be the world's most trusted ...   
4  We are an adaptive learning company that empow...   

                                job_description_text   seniority_level  \
0  OverviewUpper Hand is embarking on an exciting...        Internship   
1  Company DescriptionThe Ikigai platform unlocks...  Mid-Senior level   
2  Our CompanyChanging the world through digital ...       Entry level   
3  Waymo is an autonomous driving technology comp...       Entry level   
4  Job Title: Machine Learning EngineerLocation: ...  Mid-Senior level   

                                           job_title  
0  Internship - Machine Learning Engineer & Data ...  
1                          Machine Learning Engineer  
2                          Machine Learning Engineer  
3                Machine Learning Engineer, Training  
4                          Machine Learning Engineer

In [6]:
df.columns

Index(['Unnamed: 0', 'job_posted_date', 'company_address_locality',
       'company_address_region', 'company_name', 'company_website',
       'company_description', 'job_description_text', 'seniority_level',
       'job_title'],
      dtype='object')

In [14]:
import pandas as pd

# Assuming df is your DataFrame
grouped = df.groupby(['company_name', 'job_title'])['job_posted_date'].min().reset_index()
grouped


company_name                                job_title  \
0                    222                Machine Learning Engineer   
1             AEP Hawaii                Machine Learning Engineer   
2                AI Fund                Machine Learning Engineer   
3                AI Fund  Machine Learning Engineer - Fine Tuning   
4    AIQ.com (Alpine IQ)                        Software Engineer   
..                   ...                                      ...   
732                sync.                Machine Learning Engineer   
733           techire ai                Machine Learning Engineer   
734             thrively                     AI Software Engineer   
735             twentyAI                           Data Scientist   
736                webAI                     AI Software Engineer   

    job_posted_date  
0        2025-04-09  
1        2025-03-11  
2        2025-03-30  
3        2025-04-01  
4        2025-04-01  
..              ...  
732      2024-12-11  
733      2025-03-27  
734      2025-04-09  
735      2025-04-09  
736      2025-04-08  

[737 rows x 3 columns]

In [ ]:
# Logging in python
import logging

# configure the basic logging settings
logging.basicConfig(level=logging.DEBUG)

# Log messages in different severity settings
logging.debug("This is a debug message") # typically of interest when diagnosing  problem
logging.info("This is a info message") # things are working as expected
logging.warning("This is a warning message") #  indication that something unexpected happened
logging.error("This is an error message") # due to a more serious problem, system is not able to perform some function
logging.critical("This is a critical message") # a very serios error, indicating that the program itself may be unable to continue running

DEBUG:root:This is a debug message
INFO:root:This is a info message
ERROR:root:This is an error message
CRITICAL:root:This is a critical message


In [25]:
import logging
import os

# Reset handlers if already configured
for handler in logging.root.handlers[:]:
    logging.root.removeHandler(handler)

# Configure logging
logging.basicConfig(
    filename='app.log',
    filemode='w',
    level=logging.DEBUG,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)

# Log messages
logging.debug("This is a debug message")
logging.info("This is an info message")
logging.warning("This is a warning message")
logging.error("This is an error message")
logging.critical("This is a critical message")

print("Log file written to:", os.path.abspath("app.log"))


Log file written to: /home/wanyua/Dev/ML/Python-Machine-Learning-Tutorial/Python_for_data_science/app.log


In [30]:
import logging

# create a handler
console_handler = logging.StreamHandler()
console_handler.setFormatter(logging.Formatter(
    '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
))

# create logger for module 1
logger1 = logging.getLogger("module1")
logger1.setLevel(logging.DEBUG)
logger1.addHandler(console_handler)

# create logger for module 2
logger2 = logging.getLogger("module2")
logger2.setLevel(logging.WARNING)
logger2.addHandler(console_handler)

# Log messages with different loggers
logger1.debug("This is a debug message for module1")
logger2.warning("This is a warning message for module2")
logger2.error("This is an error message for module2")


2025-05-19 22:10:58 - module1 - DEBUG - This is a debug message for module1
2025-05-19 22:10:58 - module2 - WARNING - This is a warning message for module2
2025-05-19 22:10:58 - module2 - ERROR - This is an error message for module2
