In [3]:
# Data serialization
import json  
data = {'name': 'Sam', 'age': 34}
json_str = json.dumps(data)
print(json_str)

parsed_data = json.loads(json_str)
print(parsed_data)
print(type(parsed_data))


{"name": "Sam", "age": 34}
{'name': 'Sam', 'age': 34}
<class 'dict'>


In [5]:
# csv
import csv
with open('example.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['name', 'age'])
    writer.writerow(['Sam', 43])

# read
with open('example.csv', mode='r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['name', 'age']
['Sam', '43']


In [7]:
# datetime
from datetime import datetime, timedelta
now = datetime.now()
print(now)

yesterday = now - timedelta(days=1)
print(yesterday)

2025-05-14 14:35:28.727505
2025-05-13 14:35:28.727505


In [9]:
# time
import time

print(time.time())
time.sleep(2)
print(time.time())

1747222597.405282
1747222599.40748


In [10]:
# regular expressions
import re

pattern = r'\d+' # d -> digits
text = 'There are 123 apples'
match = re.search(pattern, text)
print(match.group())

123


In [ ]:
# file operations
# Read a file
with open('iris.csv', mode='r') as file:
    content = file.read()
    print(content)

"sepal.length","sepal.width","petal.length","petal.width","variety"
5.1,3.5,1.4,.2,"Setosa"
4.9,3,1.4,.2,"Setosa"
4.7,3.2,1.3,.2,"Setosa"
4.6,3.1,1.5,.2,"Setosa"
5,3.6,1.4,.2,"Setosa"
5.4,3.9,1.7,.4,"Setosa"
4.6,3.4,1.4,.3,"Setosa"
5,3.4,1.5,.2,"Setosa"
4.4,2.9,1.4,.2,"Setosa"
4.9,3.1,1.5,.1,"Setosa"
5.4,3.7,1.5,.2,"Setosa"
4.8,3.4,1.6,.2,"Setosa"
4.8,3,1.4,.1,"Setosa"
4.3,3,1.1,.1,"Setosa"
5.8,4,1.2,.2,"Setosa"
5.7,4.4,1.5,.4,"Setosa"
5.4,3.9,1.3,.4,"Setosa"
5.1,3.5,1.4,.3,"Setosa"
5.7,3.8,1.7,.3,"Setosa"
5.1,3.8,1.5,.3,"Setosa"
5.4,3.4,1.7,.2,"Setosa"
5.1,3.7,1.5,.4,"Setosa"
4.6,3.6,1,.2,"Setosa"
5.1,3.3,1.7,.5,"Setosa"
4.8,3.4,1.9,.2,"Setosa"
5,3,1.6,.2,"Setosa"
5,3.4,1.6,.4,"Setosa"
5.2,3.5,1.5,.2,"Setosa"
5.2,3.4,1.4,.2,"Setosa"
4.7,3.2,1.6,.2,"Setosa"
4.8,3.1,1.6,.2,"Setosa"
5.4,3.4,1.5,.4,"Setosa"
5.2,4.1,1.5,.1,"Setosa"
5.5,4.2,1.4,.2,"Setosa"
4.9,3.1,1.5,.2,"Setosa"
5,3.2,1.2,.2,"Setosa"
5.5,3.5,1.3,.2,"Setosa"
4.9,3.6,1.4,.1,"Setosa"
4.4,3,1.3,.2,"Setosa"
5.1,3.4,1.5,.2,"Seto

In [14]:
# read line by line
with open('example.csv', 'r') as file:
    for line in file:
        print(line.strip())

name,age
Sam,43


In [ ]:
# writing a file
with open('example.txt', 'a') as file: # a -> append, w -> write, w+ -> read and write
    file.write('This is my new file')
    file.write('Hello world')

# writing a list of lines to a file
lines=['First line\n', 'Second line\n', 'Third line \n']
with open('example.txt', 'a') as file:
    file.writelines(lines)

In [19]:
# Binary files
# writing to a binary file
data = b'\x00\x01\x02\x03\x04'
with open('example.bin', 'wb') as file:
    file.write(data)

In [20]:
# read binary file
with open('example.bin', 'rb') as file:
    content = file.read()
    print(content)

b'\x00\x01\x02\x03\x04'


In [21]:
with open('example.txt', 'r') as source_file:
    content = source_file.read()

with open('destination.txt', 'w') as destination_file:
    destination_file.write(content)

In [25]:
# read a text fiel and count the nuber of lines, words and characters
def count_text_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
        line_count = len(lines)
        word_count = sum(len(line.split()) for line in lines)
        char_count = sum(len(line) for line in lines)
    return line_count, word_count, char_count

file_path = 'example.txt'
lines, words, characters = count_text_file(file_path)
print(f'lines: {lines}, words: {words}, characters: {characters}')

lines: 3, words: 21, characters: 125


In [28]:
# writing then reading the fiel
with open('example2.txt', 'w+') as file:
    file.write('I love Singapore\n')
    file.write('Also Illinois\n')

    # move the file cursor to the beginning
    file.seek(0)
    content = file.read()
    print(content)

I love Singapore
Also Illinois



In [29]:
# create new directory
import os
new_directory = "package"
os.mkdir(new_directory)
print(f"Directory {new_directory} is created")

Directory package is created


In [30]:
# listing Files and directories
items = os.listdir('.')
print(items)

['python.ipynb', 'destination.txt', 'example.bin', 'example.txt', 'Recommeder_system.ipynb', 'Data', 'package', 'ETH_1h.csv', 'example2.txt', 'iris.csv', 'notebook.ipynb', 'logistic_regression.ipynb', 'classification.ipynb', 'clustering.ipynb', 'decision_tree.ipynb', 'example.csv', 'titanic.csv']


In [32]:
# Joining paths
dir_name = "new_folder"
file_name = "file.txt"
full_path = os.path.join(os.getcwd(),dir_name, file_name)
print(full_path)

/home/wanyua/Dev/ML/Python-Machine-Learning-Tutorial/Python_for_data_science/new_folder/file.txt


In [33]:
path = 'example3.txt'
if os.path.exists(path):
    print(f"The path {path} exists")
else:
    print(f"The path {path} does not exist")

The path example3.txt does not exist


In [34]:
# Checking if a path is file or directory
import os
path = 'example.txt'
if os.path.isfile(path):
    print(f"The path {path} is a file")
elif os.path.isdir(path):
    print(f"The path {path} is a directory")
else:
    print(f"The path {path} is neither a file nor a directory")


The path example.txt is a file


In [35]:
# getting the absolute path
relative_path = 'example.bin'
absolute_path = os.path.abspath(relative_path)
print(absolute_path)

/home/wanyua/Dev/ML/Python-Machine-Learning-Tutorial/Python_for_data_science/example.bin


In [37]:
# exceptions handling
try:
    file= open('example.bin', 'r')
    content = file.read()
    print(content)
except FileNotFoundError:
    print("The file does not exist")
except Exception as ex:
    print(ex)
finally:
    if 'file' in locals() and not file.closed:
        file.close()
        print('File closed')


File closed


In [ ]:
!pip install numpy
import numpy as np
arr = np.array([[1,2,3], [3,4,5], [5,4,6]])
print(arr)


  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[[1 2 3]
 [3 4 5]
 [5 4 6]]


In [2]:
arr[:1]

array([[1, 2, 3]])

In [7]:
arr[:,2]

array([3, 5, 6])

In [20]:
arr[0:2, 1:]

array([[2, 3],
       [4, 5]])

In [32]:
# standardization and normalization
data = np.array([1,2,3,4,5,6,7,8])
print(data[(data > 4) & (data<7)])
# mean and standard deviation 
# standard deviation -> tells you how much the values vary from the average
mean = np.mean(data)
standard_deviation = np.std(data) # standardization -> mean = 0, standardard deviation = 1
print(f"Mean: {mean}, Standard deviation : {standard_deviation}")


# normalize the data -> rescales values so they lie between 0 and 1
norm_data = (data - mean)/ standard_deviation
print(f"Normalized data: {norm_data}")


[5 6]
Mean: 4.5, Standard deviation : 2.29128784747792
Normalized data: [-1.52752523 -1.09108945 -0.65465367 -0.21821789  0.21821789  0.65465367
  1.09108945  1.52752523]


In [34]:
# pandas -dataframes and series
!pip install pandas
import pandas as pd

  Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
     |████████████████████████████████| 509 kB 365 kB/s eta 0:00:01
     |████████████████████████████████| 347 kB 144 kB/s eta 0:00:01


In [35]:
# series - one dimension array like object. Similar like a column in a table
data = [1,2,3,4,5]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [36]:
# creating a series from a dictionary
data = {'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data)
series_dict

a    1
b    2
c    3
dtype: int64

In [39]:
arr = [1,2,3,4.3,5.3]
ind = ['a', 'b', 'c', 'd', 'e']
pd.Series(data, index = ind)

a    1.0
b    2.0
c    3.0
d    NaN
e    NaN
dtype: float64

In [43]:
# Data frame - similar to a table or a multidimensional array
# creating a df from a dictionary
data = {
    'Name': ['Sam', 'Vule', 'Chels', 'Ros'],
    'Age': [23,23,45,43],
    'City': ["New Mexico", 'Nairobi', "Pretoria", "Cairo"]
}

print(pd.DataFrame(data))
print(np.array(pd.DataFrame(data)))

    Name  Age        City
0    Sam   23  New Mexico
1   Vule   23     Nairobi
2  Chels   45    Pretoria
3    Ros   43       Cairo
[['Sam' 23 'New Mexico']
 ['Vule' 23 'Nairobi']
 ['Chels' 45 'Pretoria']
 ['Ros' 43 'Cairo']]


In [44]:
# creating a df from a list of dictionary
data = [
    {'name': 'Sam', 'age': 25, 'city': 'new jersey'},
    {'name': 'Sam', 'age': 25, 'city': 'new jersey'},
    {'name': 'Sam', 'age': 25, 'city': 'new jersey'},
    {'name': 'Sam', 'age': 25, 'city': 'new jersey'},
    {'name': 'Sam', 'age': 25, 'city': 'new jersey'},
]

print(pd.DataFrame(data))

  name  age        city
0  Sam   25  new jersey
1  Sam   25  new jersey
2  Sam   25  new jersey
3  Sam   25  new jersey
4  Sam   25  new jersey


In [45]:
!pip install kagglehub
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ivankmk/thousand-ml-jobs-in-usa")

print("Path to dataset files:", path)

     |████████████████████████████████| 78 kB 412 kB/s eta 0:00:01
     |████████████████████████████████| 64 kB 304 kB/s eta 0:00:01
     |████████████████████████████████| 147 kB 262 kB/s eta 0:00:01
     |████████████████████████████████| 70 kB 157 kB/s eta 0:00:01
     |████████████████████████████████| 126 kB 147 kB/s eta 0:00:01
     |████████████████████████████████| 159 kB 202 kB/s eta 0:00:01


/home/wanyua/Dev/ML/Python-Machine-Learning-Tutorial/env/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|██████████| 1.60M/1.60M [00:02<00:00, 794kB/s]

Extracting model files...
Path to dataset files: /home/wanyua/.cache/kagglehub/datasets/ivankmk/thousand-ml-jobs-in-usa/versions/1


In [49]:
df = pd.read_csv('1000_ml_jobs_us.csv')
df.head()

Unnamed: 0 job_posted_date company_address_locality company_address_region  \
0           0      2024-10-31             Indianapolis                Indiana   
1           1      2025-03-14            San Francisco             California   
2           2      2025-04-09                 San Jose                     CA   
3           3      2025-03-22            Mountain View             California   
4           4      2025-03-28                   Boston          Massachusetts   

  company_name             company_website  \
0   Upper Hand       https://upperhand.com   
1       Ikigai   https://www.ikigailabs.io   
2        Adobe        http://www.adobe.com   
3        Waymo  https://waymo.com/careers/   
4          HMH        http://www.hmhco.com   

                                 company_description  \
0  Upper Hand is the leading provider of full-sui...   
1  Built upon years of MIT research, Ikigai is a ...   
2  Adobe is the global leader in digital media an...   
3  On the journey to be the world's most trusted ...   
4  We are an adaptive learning company that empow...   

                                job_description_text   seniority_level  \
0  OverviewUpper Hand is embarking on an exciting...        Internship   
1  Company DescriptionThe Ikigai platform unlocks...  Mid-Senior level   
2  Our CompanyChanging the world through digital ...       Entry level   
3  Waymo is an autonomous driving technology comp...       Entry level   
4  Job Title: Machine Learning EngineerLocation: ...  Mid-Senior level   

                                           job_title  
0  Internship - Machine Learning Engineer & Data ...  
1                          Machine Learning Engineer  
2                          Machine Learning Engineer  
3                Machine Learning Engineer, Training  
4                          Machine Learning Engineer

In [ ]:
df.loc[2] # this is a row

Unnamed: 0                                                                  2
job_posted_date                                                    2025-04-09
company_address_locality                                             San Jose
company_address_region                                                     CA
company_name                                                            Adobe
company_website                                          http://www.adobe.com
company_description         Adobe is the global leader in digital media an...
job_description_text        Our CompanyChanging the world through digital ...
seniority_level                                                   Entry level
job_title                                           Machine Learning Engineer
Name: 2, dtype: object

In [ ]:
df.iloc[0:,3] # column 3

0            Indiana
1         California
2                 CA
3         California
4      Massachusetts
           ...      
992               CA
993            Texas
994               NY
995               CA
996    Massachusetts
Name: company_address_region, Length: 997, dtype: object

In [64]:
# remove a column
df.drop('Unnamed: 0', axis=1, inplace = True)
df.columns

Index(['job_posted_date', 'company_address_locality', 'company_address_region',
       'company_name', 'company_website', 'company_description',
       'job_description_text', 'seniority_level', 'job_title'],
      dtype='object')