In [93]:
names = ["Sam", "Obed", "Steve", "Kiarie", "Martha"]

for name in names:
    print(f"Hello  {name}, we are happy to have you!")

Hello  Sam, we are happy to have you!
Hello  Obed, we are happy to have you!
Hello  Steve, we are happy to have you!
Hello  Kiarie, we are happy to have you!
Hello  Martha, we are happy to have you!


### Lists

In [94]:
new_list = []
names = list()
print(names)
names.append("Sam")
print(names)

[]
['Sam']


In [95]:
colors = ["red", "blue", "green", "yellow"]
print("White" in colors)
print("red" in colors)
colors.insert(2, "purple")
print(colors)

False
True
['red', 'blue', 'purple', 'green', 'yellow']


In [96]:
for color in colors:
    print(color)

red
blue
purple
green
yellow


In [97]:
print(colors[:1])

['red']


In [98]:
# Creating a tuple
fruits = ("apple", "banana", "cherry")
print(fruits)  # Output: ('apple', 'banana', 'cherry')

# Accessing an item by index
print(fruits[1])  # Output: 'banana'

# Tuples are immutable, so you cannot add or remove items
# fruits.append("orange")  # This will raise an AttributeError

('apple', 'banana', 'cherry')
banana


In [99]:
# Creating a list
fruits = ["apple", "banana", "cherry"]
print(fruits)  # Output: ['apple', 'banana', 'cherry']

# Adding an item to the list
fruits.append("orange")
print(fruits)  # Output: ['apple', 'banana', 'cherry', 'orange']

# Accessing an item by index
print(fruits[1])  # Output: 'banana'

# Removing an item from the list
fruits.remove("banana")
print(fruits)  # Output: ['apple', 'cherry', 'orange']



['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry', 'orange']
banana
['apple', 'cherry', 'orange']


In [100]:
# Creating a dictionary
fruit_colors = {"apple": "red", "banana": "yellow", "cherry": "red"}
print(fruit_colors)  # Output: {'apple': 'red', 'banana': 'yellow', 'cherry': 'red'}

# Accessing a value by key
print(fruit_colors["banana"])  # Output: 'yellow'

# Adding a new key-value pair
fruit_colors["orange"] = "orange"
print(fruit_colors)  # Output: {'apple': 'red', 'banana': 'yellow', 'cherry': 'red', 'orange': 'orange'}

# Removing a key-value pair
del fruit_colors["banana"]
print(fruit_colors)  # Output: {'apple': 'red', 'cherry': 'red', 'orange': 'orange'}

{'apple': 'red', 'banana': 'yellow', 'cherry': 'red'}
yellow
{'apple': 'red', 'banana': 'yellow', 'cherry': 'red', 'orange': 'orange'}
{'apple': 'red', 'cherry': 'red', 'orange': 'orange'}


In [101]:
# String concatenation
greeting = "Hello"
name = "Alice"
message = greeting + " " + name
print(message)  # Output: Hello Alice

# String formatting using f-strings
age = 30
formatted_message = f"{name} is {age} years old."
print(formatted_message)  # Output: Alice is 30 years old.

# String slicing
substring = message[0:5]
print(substring)  # Output: Hello

# String methods
upper_case_message = message.upper()
print(upper_case_message)  # Output: HELLO ALICE

lower_case_message = message.lower()
print(lower_case_message)  # Output: hello alice

# Checking if a substring is in a string
contains_hello = "Hello" in message
print(contains_hello)  # Output: True

# Replacing a substring
new_message = message.replace("Alice", "Bob")
print(new_message)  # Output: Hello Bob

Hello Alice
Alice is 30 years old.
Hello
HELLO ALICE
hello alice
True
Hello Bob


### Sets, Tuples and Lists
* Lists -> ordered mutable collection of items. Ex. marks = [1,2,2,3,4]
* Tuple -> ordered immutable collection of items. Ex. marks =(1,2,2,3,4)
* Sets -> Unordered mutable collection of unique items. Ex. marks = {1,2,3,4}

In [102]:
# List example
my_list = [1, 2, 3, 4, 5]
print("List:", my_list)  # Output: List: [1, 2, 3, 4, 5]

# Lists are mutable, meaning you can change their content
my_list.append(6)
print("List after append:", my_list)  # Output: List after append: [1, 2, 3, 4, 5, 6]

# Tuple example
my_tuple = (1, 2, 3, 4, 5)
print("Tuple:", my_tuple)  # Output: Tuple: (1, 2, 3, 4, 5)

# Tuples are immutable, meaning you cannot change their content
# my_tuple.append(6)  # This will raise an AttributeError

# Set example
my_set = {1, 2, 3, 4, 5}
print("Set:", my_set)  # Output: Set: {1, 2, 3, 4, 5}

# Sets are mutable, but they do not allow duplicate elements
my_set.add(6)
print("Set after add:", my_set)  # Output: Set after add: {1, 2, 3, 4, 5, 6}
my_set.add(3)  # Adding a duplicate element has no effect
print("Set after adding duplicate:", my_set)  # Output: Set after adding duplicate: {1, 2, 3, 4, 5, 6}

List: [1, 2, 3, 4, 5]
List after append: [1, 2, 3, 4, 5, 6]
Tuple: (1, 2, 3, 4, 5)
Set: {1, 2, 3, 4, 5}
Set after add: {1, 2, 3, 4, 5, 6}
Set after adding duplicate: {1, 2, 3, 4, 5, 6}


### Anonymous lamda

In [103]:
# function without a name
multiply = lambda x, y: x * y
print(multiply(4, 5))

sum = lambda x, y: x + y
print(sum(4, 5))

remainder = lambda x, y: x % y
print(remainder(23, 5))

20
9
3


In [104]:
def test(n):
    return lambda x: x * n

test_1 = test(18797)
print(test_1(108239))

2034568483


In [105]:
message = "DeepSeek is taking on OpenAI"
for item in message:
    if item == "X":
        break

else: 
    print("There is no 'X' in the message")

There is no 'X' in the message


In [106]:
# password checking program
attempts = 0
while attempts < 3:
    password = input("Enter your password: ")
    if password == "password":
        print("Access granted")
        break
    else:
        print("Access denied")
        attempts += 1
if attempts == 3:
    print("Access denied. You have exceeded the maximum number of attempts")

Access granted


In [107]:
class Car:
    color = "red"
    make = "Toyota"
    model = "Corolla"
model_1 = Car()
print(model_1.color, model_1.make, model_1.model)



red Toyota Corolla


#### Class

In [108]:
class Vehicle:
    def __init__(self, color, make, model):
        self.color = color
        self.make = make
        self.model = model

    def display_vehicle(self):
        print(f"Color: {self.color}")
        print(f"Make: {self.make}")
        print(f"Model: {self.model}")
    
    def change_color(self, new_color):
        self.color = new_color
    
    @staticmethod
    def honk():
        print("Beep beep")
    
    @classmethod
    def get_vehicle(cls):
        return cls("red", "Toyota", "Corolla")

vehicle_1 = Vehicle("red", "Toyota", "Corolla")
vehicle_1.display_vehicle()

vehicle_1.change_color("blue")
vehicle_1.display_vehicle()

Vehicle.honk() # Output: Beep beep
vehicle_2 = Vehicle.get_vehicle()

vehicle_2.display_vehicle()
vehicle_2.get_vehicle()

del vehicle_2 


Color: red
Make: Toyota
Model: Corolla
Color: blue
Make: Toyota
Model: Corolla
Beep beep
Color: red
Make: Toyota
Model: Corolla


### Inheritance

In [109]:
class Animal:
    def __init__(self, species, sound):
        self.species = species
        self.sound = sound

    def make_sound(self):
        print(self.sound)

    def display_species(self):
        print(self.species)

mammmal = Animal("Mammal", "Roar")
mammmal.display_species()
mammmal.make_sound()

class Dog(Animal):
    def __init__(self, species, sound, breed):
        super().__init__(species, sound) # Call the __init__ method of the parent class
        self.breed = breed

    def display_breed(self):
        print(self.breed)

dog = Dog("Mammal", "Bark", "Bulldog")
dog.display_species()
dog.make_sound()
dog.display_breed()

Mammal
Roar
Mammal
Bark
Bulldog


### List comprehension

In [110]:
# [expression for item in iterable if condition]
[print(i) for i in range(10) if i % 2 == 0]

0
2
4
6
8


[None, None, None, None, None]

In [111]:
# Set comprehension
set_comprehension = {x**2 for x in range(10)}
print("Set comprehension:", set_comprehension)

# Tuple comprehension (Note: There is no direct tuple comprehension, but you can use a generator expression and convert it to a tuple)
tuple_comprehension = tuple(x**2 for x in range(10))
print("Tuple comprehension:", tuple_comprehension)

Set comprehension: {0, 1, 64, 4, 36, 9, 16, 49, 81, 25}
Tuple comprehension: (0, 1, 4, 9, 16, 25, 36, 49, 64, 81)


In [112]:
# Dictionary comprehension
squares = {x: x**2 for x in range(10)}
print("Dictionary comprehension:", squares)

Dictionary comprehension: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


### Built-in modules in Python

In [113]:
import sys

# List all built-in modules
builtin_modules = sys.builtin_module_names
print(builtin_modules)
help('modules')

('_abc', '_ast', '_bisect', '_blake2', '_codecs', '_collections', '_csv', '_datetime', '_elementtree', '_functools', '_heapq', '_imp', '_io', '_locale', '_md5', '_operator', '_pickle', '_posixsubprocess', '_random', '_sha1', '_sha256', '_sha3', '_sha512', '_signal', '_socket', '_sre', '_stat', '_statistics', '_string', '_struct', '_symtable', '_thread', '_tracemalloc', '_warnings', '_weakref', 'array', 'atexit', 'binascii', 'builtins', 'cmath', 'errno', 'faulthandler', 'fcntl', 'gc', 'grp', 'itertools', 'marshal', 'math', 'posix', 'pwd', 'pyexpat', 'select', 'spwd', 'sys', 'syslog', 'time', 'unicodedata', 'xxsubtype', 'zlib')

Please wait a moment while I gather a list of all available modules...

IPython             array               importlib           resource
PIL                 ast                 importlib_metadata  retrying
__future__          asttokens           importlib_resources rlcompleter
_abc                asynchat            inspect             runpy
_ast             

In [114]:
import random #Altanatively: from random import randint, random, choice, shuffle

# Generate a random integer between 1 and 10
random_int = random.randint(4, 9000000)
print(f"Random integer between 1 and 9000000: {random_int}")

# Generate a random float between 0 and 1
random_float = random.random()
print(f"Random float between 0 and 1: {random_float}")

# Choose a random element from a list
colors = ["red", "blue", "green", "yellow","grey", "black" ]
random_color = random.choice(colors)
print(f"Random color: {random_color}")

# Shuffle a list
random.shuffle(colors)
print(f"Shuffled colors: {colors}")

print("Done!")

Random integer between 1 and 9000000: 6407232
Random float between 0 and 1: 0.6921351393514883
Random color: red
Shuffled colors: ['yellow', 'green', 'red', 'blue', 'grey', 'black']
Done!


#### Math module

In [115]:
import math

math.sqrt(16) # Output: 4.0
print(math.e)
print(math.pi)
print(math.degrees(math.pi))
print(math.radians(180))
math.sin(83.2)
math.acos(0.5)

2.718281828459045
3.141592653589793
180.0
3.141592653589793


1.0471975511965979

In [116]:
import math

angle = 0.5  # Example angle in radians
inverse_cosine = math.acos(angle)
print(f"The inverse cosine (arccos) of {angle} is {inverse_cosine} radians")

The inverse cosine (arccos) of 0.5 is 1.0471975511965979 radians


In [117]:
import statistics
statistics.mean([1, 2, 3, 4, 4])  # Output: 2.8
statistics.median([1, 2, 3, 4, 4])  # Output: 3
statistics.NormalDist(mu=0, sigma=1).pdf(0)  # Output: 0.3989422804014327
statistics.mode([1, 2, 3, 4, 4])  # Output: 4
statistics.stdev([1, 2, 3, 4, 4])  # Output: 1.3038404810405297

1.3038404810405297

In [118]:
# In Python, there are several types of errors that you might encounter. Here are some common ones:

# 1. **SyntaxError**: This occurs when the code is not written in proper Python syntax.
if True:
    print("Hello")  # Missing colon (:) after the if statement

# 2. **IndentationError**: This occurs when the code is not properly indented.
def my_function():
    print("Hello")  # This line should be indented

# 3. **NameError**: This occurs when a variable or function name is not found.
print(x)  # x is not defined

# 4. **TypeError**: This occurs when an operation or function is applied to an object of inappropriate type.
print("Hello" + 5)  # Cannot concatenate a string and an integer

# 5. **ValueError**: This occurs when a function receives an argument of the right type but inappropriate value.
int("Hello")  # Cannot convert a string that is not a number to an integer

# 6. **IndexError**: This occurs when trying to access an element from a list using an index that is out of range.
my_list = [1, 2, 3]
print(my_list[5])  # Index 5 is out of range

# 7. **KeyError**: This occurs when trying to access a dictionary with a key that does not exist.
my_dict = {"a": 1, "b": 2}
print(my_dict["c"])  # Key 'c' does not exist

# 8. **AttributeError**: This occurs when trying to access an attribute that does not exist for an object.
my_list = [1, 2, 3]
my_list.append(4)
my_list.push(5)  # 'list' object has no attribute 'push'

# 9. **ImportError**: This occurs when an import statement fails to find the module definition or when a from ... import fails to find a name that is to be imported.
import non_existent_module  # No module named 'non_existent_module'

# 10. **ZeroDivisionError**: This occurs when a division or modulo operation is performed with zero as the divisor.
print(10 / 0)  # Division by zero

# These are just a few examples of common errors in Python. Understanding these errors can help you debug your code more effectively.

Hello


NameError: name 'x' is not defined

In [ ]:
try:
    # Code that may raise an exception
    result = 10 / 0
except ZeroDivisionError as e:
    # Code to handle the exception
    print(f"Error: {e}")
else:
    # Code to execute if no exception is raised
    print("No exceptions were raised.")
finally:
    # Code to execute regardless of whether an exception was raised or not
    print("This block is always executed.")

# Example with multiple exceptions
try:
    value = int("Hello")
except ValueError as e:
    print(f"ValueError: {e}")
except TypeError as e:
    print(f"TypeError: {e}")

In [72]:
import io

new_text = "Learning Python is fun!"
with open("example.txt", "w") as file:
    file.write(new_text)
    
with open("example.txt", "r") as file:
    content = file.read()
    print(content)

with open("example.txt", "a") as file:
    file.write("\nI love Python!")

# Move the cursor to the beginning of the file
# file.seek(0)

# Reopen the file in read mode and read the updated content
with open("example.txt", "r") as file:
    updated_content = file.read()
    print(updated_content)

Learning Python is fun!
Learning Python is fun!
I love Python!


In [73]:
import os

# Get the current working directory
current_directory = os.getcwd()
print(f"Current Directory: {current_directory}")

# List all files and directories in the current directory
files_and_directories = os.listdir(current_directory)
print(f"Files and Directories: {files_and_directories}")

# Create a new directory
new_directory = "new_folder"
os.makedirs(new_directory, exist_ok=True)
print(f"Created new directory: {new_directory}")

# Rename a directory
renamed_directory = "renamed_folder"
os.rename(new_directory, renamed_directory)
print(f"Renamed directory to: {renamed_directory}")

# Remove a directory
os.rmdir(renamed_directory)
print(f"Removed directory: {renamed_directory}")

# Get the value of an environment variable
home_directory = os.getenv("HOME")
print(f"Home Directory: {home_directory}")

# Set an environment variable
os.environ["MY_VARIABLE"] = "my_value"
print(f"MY_VARIABLE: {os.getenv('MY_VARIABLE')}")

Current Directory: /home/wanyua/Dev/ML/Python-Machine-Learning-Tutorial/Python
Files and Directories: ['example.txt', 'python_basics.ipynb', 'app.py']
Created new directory: new_folder
Renamed directory to: renamed_folder
Removed directory: renamed_folder
Home Directory: /home/wanyua
MY_VARIABLE: my_value


In [74]:
import shutil

# Copy a file
shutil.copy("example.txt", "example_copy.txt")
print("File copied successfully.")

# Move a file
shutil.move("example_copy.txt", "example_moved.txt")
print("File moved successfully.")

# Remove a file
os.remove("example_moved.txt")
print("File removed successfully.")

File copied successfully.
File moved successfully.
File removed successfully.


In [75]:
import copy

# Original list
original_list = [1, 2, [3, 4], 5]

# Shallow copy - modifications in the copied object can affect the original if it contains mutable objects.

shallow_copy = copy.copy(original_list)

# Deep copy - Changes in the copied object do not affect the original.

deep_copy = copy.deepcopy(original_list)

# Modify the original list
original_list[2][0] = 'Changed'

print("Original list:", original_list)  # Output: [1, 2, ['Changed', 4], 5]
print("Shallow copy:", shallow_copy)    # Output: [1, 2, ['Changed', 4], 5]
print("Deep copy:", deep_copy)          # Output: [1, 2, [3, 4], 5]

Original list: [1, 2, ['Changed', 4], 5]
Shallow copy: [1, 2, ['Changed', 4], 5]
Deep copy: [1, 2, [3, 4], 5]


In [ ]:
# !pip install send2trash
import send2trash

# Send a file to the trash
send2trash.send2trash("example.txt")
print("File sent to trash successfully.")

# Send a directory to the trash
send2trash.send2trash("new_folder")
print("Directory sent to trash successfully.")

In [77]:
import zipfile
import os

new_file = open('example_moved.txt', 'w')
# Create a zip file
with zipfile.ZipFile('example.zip', 'w') as zipf:
    zipf.write('example.txt')
    zipf.write('example_moved.txt')

print("Files zipped successfully.")

# Unzip the file
with zipfile.ZipFile('example.zip', 'r') as zipf:
    zipf.extractall('extracted_files')

print("Files unzipped successfully.")

# List the contents of the extracted directory
extracted_files = os.listdir('extracted_files')
print(f"Extracted files: {extracted_files}")

Files zipped successfully.
Files unzipped successfully.
Extracted files: ['example.txt', 'example_moved.txt']


### Numpy arrays

In [81]:
import numpy as np

# Create a NumPy array from a list
array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)

# Create a NumPy array with a range of values
array_range = np.arange(9)
print("Array with range of values:", array_range)

# Create a NumPy array with zeros
array_zeros = np.zeros((3, 3))
print("Array with zeros:\n", array_zeros)

# Create a NumPy array with ones
array_ones = np.ones((2, 4))
print("Array with ones:\n", array_ones)

# Create a NumPy array with random values
array_random = np.random.random((4, 4))
print("Array with random values:\n", array_random)

# Perform basic arithmetic operations on NumPy arrays
array_sum = array_from_list + 10
print("Array after addition:", array_sum)

array_product = array_from_list * 2
print("Array after multiplication:", array_product)

# Access elements of a NumPy array
element = array_from_list[2]
print("Element at index 2:", element)

# Slicing a NumPy array
array_slice = array_from_list[1:4]
print("Sliced array:", array_slice)

Array from list: [1 2 3 4 5]
Array with range of values: [0 1 2 3 4 5 6 7 8]
Array with zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array with ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with random values:
 [[0.45037838 0.04657062 0.21650479 0.62893839]
 [0.45737238 0.37754599 0.12188324 0.77510976]
 [0.69889786 0.23656815 0.6579891  0.90588845]
 [0.81050128 0.81018526 0.65894468 0.48645593]]
Array after addition: [11 12 13 14 15]
Array after multiplication: [ 2  4  6  8 10]
Element at index 2: 3
Sliced array: [2 3 4]


In [84]:
marks = [12.1, 13.2, 14.3, 15.4, 16.5]
np_marks = np.array(marks)
double_marks = np_marks * 2
print(f"Double marks: {double_marks}")

Double marks: [24.2 26.4 28.6 30.8 33. ]


#### 1-Dimensional Numpy arrays Operations

In [86]:
# Create a 1-dimensional NumPy array
array_1d = np.array([10, 20, 30, 40, 50])

# Sum of all elements
sum_elements = np.sum(array_1d)
print(f"Sum of elements: {sum_elements}")

# Mean of all elements
mean_elements = np.mean(array_1d)
print(f"Mean of elements: {mean_elements}")

# Standard deviation of all elements
std_deviation = np.std(array_1d)
print(f"Standard deviation of elements: {std_deviation}")

# Minimum and maximum elements
min_element = np.min(array_1d)
max_element = np.max(array_1d)
print(f"Minimum element: {min_element}")
print(f"Maximum element: {max_element}")

# Index of the minimum and maximum elements
min_index = np.argmin(array_1d) # returns the indices of the minimum values along an axis
max_index = np.argmax(array_1d) # returns the indices of the maximum values along an axis
print(f"Index of minimum element: {min_index}")
print(f"Index of maximum element: {max_index}")

# Cumulative sum of elements
cumulative_sum = np.cumsum(array_1d)
print("The one dimensional array is: ", array_1d)
print(f"Cumulative sum of elements: {cumulative_sum}")

# Sorting the array
sorted_array = np.sort(array_1d)
print(f"Sorted array: {sorted_array}")

Sum of elements: 150
Mean of elements: 30.0
Standard deviation of elements: 14.142135623730951
Minimum element: 10
Maximum element: 50
Index of minimum element: 0
Index of maximum element: 4
The one dimensional array is:  [10 20 30 40 50]
Cumulative sum of elements: [ 10  30  60 100 150]
Sorted array: [10 20 30 40 50]


In [87]:
# Square root of each element
sqrt_array = np.sqrt(array_1d)
print(f"Square root of elements: {sqrt_array}")

# Exponential (e^x) of each element
exp_array = np.exp(array_1d)
print(f"Exponential of elements: {exp_array}")

# Natural logarithm (ln) of each element
log_array = np.log(array_1d)
print(f"Natural logarithm of elements: {log_array}")

# Sine of each element (assuming elements are in radians)
sin_array = np.sin(array_1d)
print(f"Sine of elements: {sin_array}")

# Cosine of each element (assuming elements are in radians)
cos_array = np.cos(array_1d)
print(f"Cosine of elements: {cos_array}")

# Tangent of each element (assuming elements are in radians)
tan_array = np.tan(array_1d)
print(f"Tangent of elements: {tan_array}")

Square root of elements: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponential of elements: [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
Natural logarithm of elements: [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
Sine of elements: [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
Cosine of elements: [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
Tangent of elements: [ 0.64836083  2.23716094 -6.4053312  -1.11721493 -0.27190061]


#### Creating N-Dimensional numpy arrays


In [97]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

ones_np = np.ones((3, 5))
print(ones_np)

random_np = np.random.random((2, 6)) # Create a 2x6 array with random values between 0 and 1
print(random_np)

cat_marks = np.random.randint(30, 100, 10) # Generate 10 random integers between 0 and 100   
print(f"Cat marks: {cat_marks}")


[[1 2 3]
 [4 5 6]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.64096872 0.1000776  0.52787721 0.0041767  0.68893038 0.10214932]
 [0.19361158 0.89380118 0.68775575 0.79303401 0.04258087 0.31439545]]
Cat marks: [99 58 80 89 58 31 67 68 90 61]


In [103]:
x = np.array([[23,33,34],[1, 2, 23]])
y = np.array([[43,2,90],[23, 34, 3]])
print(f"Sum of x and y: {x + y}")

Sum of x and y: [[ 66  35 124]
 [ 24  36  26]]


In [102]:
# Dot product of two arrays
dot_product = np.dot(x, y.T)  # Transpose y to match the dimensions
print(f"Dot product of x and y:\n{dot_product}")

# Cross product of two arrays
# Note: Cross product is only defined for 3-dimensional vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
cross_product = np.cross(vector_a, vector_b)
print(f"Cross product of vector_a and vector_b: {cross_product}")

Dot product of x and y:
[[4115 1753]
 [2117  160]]
Cross product of vector_a and vector_b: [-3  6 -3]


In [104]:
# Accessing elements in a 2D NumPy array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access a specific element
element = matrix[1, 2]  # Access the element at row index 1 and column index 2
print(f"Element at row 1, column 2: {element}")

# Access a specific row
row = matrix[1, :]  # Access the entire row at index 1
print(f"Row at index 1: {row}")

# Access a specific column
column = matrix[:, 2]  # Access the entire column at index 2
print(f"Column at index 2: {column}")

# Access a submatrix
submatrix = matrix[0:2, 1:3]  # Access the submatrix from row indices 0 to 1 and column indices 1 to 2
print(f"Submatrix from rows 0 to 1 and columns 1 to 2:\n{submatrix}")

Element at row 1, column 2: 6
Row at index 1: [4 5 6]
Column at index 2: [3 6 9]
Submatrix from rows 0 to 1 and columns 1 to 2:
[[2 3]
 [5 6]]


### Reshape an array

In [112]:
new_data = np.array([1,2,3,4,5,6])
reshaped_data = new_data.reshape(2,3)
print(reshaped_data)

[[1 2 3]
 [4 5 6]]


In [114]:
t = np.random.randint(34, 78, 44)
print(t)
reshaped_t = t.reshape(4,11)
print(reshaped_t)

[46 69 37 35 47 65 60 52 38 38 57 54 38 35 44 66 49 49 43 58 35 60 37 54
 45 48 57 73 64 75 68 61 49 49 70 51 71 60 72 41 36 75 63 59]
[[46 69 37 35 47 65 60 52 38 38 57]
 [54 38 35 44 66 49 49 43 58 35 60]
 [37 54 45 48 57 73 64 75 68 61 49]
 [49 70 51 71 60 72 41 36 75 63 59]]


In [122]:
r= np.ones((33, 3,8)) # 33 is no. of arrays, 3 = rows, 8 = columns
print(r)

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.

In [1]:
import pandas as pd
# Pandas series -  one-dimensional labeled array that can hold data of any type (integers, floats, strings, etc.). It is similar to a column in a spreadsheet or a list but with an index attached to each value.
# Creating a Pandas Series from a list
data = [10, 20, 30, 40, 50]
series = pd.Series(data)
print("Pandas Series from list:")
print(series)

# Creating a Pandas Series from a dictionary
data_dict = {'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data_dict)
print("\nPandas Series from dictionary:")
print(series_dict)

# Accessing elements in a Pandas Series
print("\nElement at index 2:", series[2])
print("Element with index 'b':", series_dict['b'])

# Performing operations on a Pandas Series
print("\nSeries after addition:")
print(series + 5)

print("\nSeries after multiplication:")
print(series * 2)

Pandas Series from list:
0    10
1    20
2    30
3    40
4    50
dtype: int64

Pandas Series from dictionary:
a    1
b    2
c    3
dtype: int64

Element at index 2: 30
Element with index 'b': 2

Series after addition:
0    15
1    25
2    35
3    45
4    55
dtype: int64

Series after multiplication:
0     20
1     40
2     60
3     80
4    100
dtype: int64


In [ ]:
#  Pandas series is like a single column of data. It has only one column and index.
#  Pandas DataFrame is like a table with rows and columns. It has two dimensions and an index.

In [6]:
# Pandas DataFrame is a two-dimensional, labeled data structure similar to a table in a database, a spreadsheet, or a dictionary of Series objects
colors = ['red', 'blue', 'green', 'yellow', 'black']
degrees = [12, 23, 34, 45, 56]
numbers = [1, 2, 3, 4, 5]


# Create a Pandas DataFrame from the lists above
new_df = pd.DataFrame({'Colors': colors, 'Degrees': degrees, 'Numbers': numbers},
                      index=range(1, 6))
print(new_df)


   Colors  Degrees  Numbers
1     red       12        1
2    blue       23        2
3   green       34        3
4  yellow       45        4
5   black       56        5


In [ ]:
import pandas as pd

# Create the first DataFrame
new_df = pd.DataFrame({
    'Colors': ['red', 'blue', 'green', 'yellow', 'black'],
    'Degrees': [12, 23, 34, 45, 56],
    'Numbers': [1, 2, 3, 4, 5]
})

# Create a new DataFrame to append
new_data = {
    'Colors': ['purple', 'orange'],
    'Degrees': [67, 78],
    'Numbers': [6, 7]
}
new_df2 = pd.DataFrame(new_data)

# Append using pd.concat()
appended_df = pd.concat([new_df, new_df2], ignore_index=True)
print("\nAppended DataFrame:")
print(appended_df)

# Create a new DataFrame with medical data
medical_data = {
    'PatientID': [101, 102],
    'Age': [45, 50],
    'Diagnosis': ['Hypertension', 'Diabetes']
}
medical_df = pd.DataFrame(medical_data)

# Append the medical DataFrame (columns don't match, so NaNs will appear)
final_df = pd.concat([appended_df, medical_df], ignore_index=True)
print("\nFinal DataFrame:")
print(final_df)



Appended DataFrame:
   Colors  Degrees  Numbers
0     red       12        1
1    blue       23        2
2   green       34        3
3  yellow       45        4
4   black       56        5
5  purple       67        6
6  orange       78        7

Final DataFrame:
   Colors  Degrees  Numbers  PatientID   Age     Diagnosis
0     red     12.0      1.0        NaN   NaN           NaN
1    blue     23.0      2.0        NaN   NaN           NaN
2   green     34.0      3.0        NaN   NaN           NaN
3  yellow     45.0      4.0        NaN   NaN           NaN
4   black     56.0      5.0        NaN   NaN           NaN
5  purple     67.0      6.0        NaN   NaN           NaN
6  orange     78.0      7.0        NaN   NaN           NaN
7     NaN      NaN      NaN      101.0  45.0  Hypertension
8     NaN      NaN      NaN      102.0  50.0      Diabetes


In [10]:
! pip install lxml

     |████████████████████████████████| 5.0 MB 1.0 MB/s eta 0:00:01


In [50]:
import pandas as pd
new_url = "https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_area"
countries = pd.read_html(new_url, header=0, index_col=0)

print(f"Number of tables: {len(countries)}")
table_1 = countries[0]
table_1.head()
table_of_countries = countries[1]
table_of_countries

Number of tables: 4


Country / dependency         Total in km2 (mi2)  \
NaN                                        Earth  510,072,000 (196,940,000)   
1                                         Russia     17,098,246 (6,601,667)   
NaN                                   Antarctica     14,200,000 (5,480,000)   
2                                         Canada      9,984,670 (3,855,100)   
3/4 [e]                                    China      9,596,960 (3,705,410)   
...                                          ...                        ...   
NaN      Ashmore and Cartier Islands (Australia)                  5.0 (1.9)   
NaN                Coral Sea Islands (Australia)                  3.0 (1.2)   
NaN                   Spratly Islands (disputed)                 2.0 (0.77)   
194                                       Monaco                 2.0 (0.77)   
195                                 Vatican City                0.49 (0.19)   

                Land in km2 (mi2)         Water in km2 (mi2)  % water  \
NaN      148,940,000 (57,506,000)  361,132,000 (139,434,000)     70.8   
1          16,376,870 (6,323,142)          721,380 (278,530)      4.2   
NaN        14,200,000 (5,480,000)                          0      0.0   
2           9,093,507 (3,511,021)          891,163 (344,080)      8.9   
3/4 [e]     9,326,410 (3,600,950)          270,550 (104,460)      2.8   
...                           ...                        ...      ...   
NaN                     5.0 (1.9)                          0      0.0   
NaN                     3.0 (1.2)                          0      0.0   
NaN                    2.0 (0.77)                          0      0.0   
194                    2.0 (0.77)                          0      0.0   
195                   0.49 (0.19)                          0      0.0   

        Unnamed: 6  
NaN            NaN  
1              [b]  
NaN            [c]  
2              [d]  
3/4 [e]        [f]  
...            ...  
NaN            [q]  
NaN           [db]  
NaN           [55]  
194           [dc]  
195           [dd]  

[264 rows x 6 columns]

In [51]:
table_of_countries.shape

(264, 6)

In [52]:
table_of_countries.columns

Index(['Country / dependency', 'Total in km2 (mi2)', 'Land in km2 (mi2)',
       'Water in km2 (mi2)', '% water', 'Unnamed: 6'],
      dtype='object')

In [121]:
table_of_countries.describe()

Water_percentage
count        255.000000
mean           2.757255
std            7.022754
min            0.000000
25%            0.000000
50%            0.700000
75%            2.600000
max           70.800000

In [122]:
df = table_of_countries # Assign the DataFrame to a variable
# Rename columns
df.columns = ['Country', 'Total_area', 'Land_area', 'Water_area', 'Water_percentage', 'Notes']
df

Country                 Total_area  \
NaN                                        Earth  510,072,000 (196,940,000)   
1                                         Russia     17,098,246 (6,601,667)   
NaN                                   Antarctica     14,200,000 (5,480,000)   
2                                         Canada      9,984,670 (3,855,100)   
3/4 [e]                                    China      9,596,960 (3,705,410)   
...                                          ...                        ...   
NaN      Ashmore and Cartier Islands (Australia)                  5.0 (1.9)   
NaN                Coral Sea Islands (Australia)                  3.0 (1.2)   
NaN                   Spratly Islands (disputed)                 2.0 (0.77)   
194                                       Monaco                 2.0 (0.77)   
195                                 Vatican City                0.49 (0.19)   

                        Land_area                 Water_area  \
NaN      148,940,000 (57,506,000)  361,132,000 (139,434,000)   
1          16,376,870 (6,323,142)          721,380 (278,530)   
NaN        14,200,000 (5,480,000)                          0   
2           9,093,507 (3,511,021)          891,163 (344,080)   
3/4 [e]     9,326,410 (3,600,950)          270,550 (104,460)   
...                           ...                        ...   
NaN                     5.0 (1.9)                          0   
NaN                     3.0 (1.2)                          0   
NaN                    2.0 (0.77)                          0   
194                    2.0 (0.77)                          0   
195                   0.49 (0.19)                          0   

         Water_percentage Notes  
NaN                  70.8   NaN  
1                     4.2   [b]  
NaN                   0.0   [c]  
2                     8.9   [d]  
3/4 [e]               2.8   [f]  
...                   ...   ...  
NaN                   0.0   [q]  
NaN                   0.0  [db]  
NaN                   0.0  [55]  
194                   0.0  [dc]  
195                   0.0  [dd]  

[264 rows x 6 columns]

In [123]:
# Drop irrevant columns
df = df.drop(columns=['Notes'])

In [124]:
df

Country                 Total_area  \
NaN                                        Earth  510,072,000 (196,940,000)   
1                                         Russia     17,098,246 (6,601,667)   
NaN                                   Antarctica     14,200,000 (5,480,000)   
2                                         Canada      9,984,670 (3,855,100)   
3/4 [e]                                    China      9,596,960 (3,705,410)   
...                                          ...                        ...   
NaN      Ashmore and Cartier Islands (Australia)                  5.0 (1.9)   
NaN                Coral Sea Islands (Australia)                  3.0 (1.2)   
NaN                   Spratly Islands (disputed)                 2.0 (0.77)   
194                                       Monaco                 2.0 (0.77)   
195                                 Vatican City                0.49 (0.19)   

                        Land_area                 Water_area  Water_percentage  
NaN      148,940,000 (57,506,000)  361,132,000 (139,434,000)              70.8  
1          16,376,870 (6,323,142)          721,380 (278,530)               4.2  
NaN        14,200,000 (5,480,000)                          0               0.0  
2           9,093,507 (3,511,021)          891,163 (344,080)               8.9  
3/4 [e]     9,326,410 (3,600,950)          270,550 (104,460)               2.8  
...                           ...                        ...               ...  
NaN                     5.0 (1.9)                          0               0.0  
NaN                     3.0 (1.2)                          0               0.0  
NaN                    2.0 (0.77)                          0               0.0  
194                    2.0 (0.77)                          0               0.0  
195                   0.49 (0.19)                          0               0.0  

[264 rows x 5 columns]

In [125]:
#  Drop non-country rows 
df = df[df['Country'] != 'Earth']
df = df[df['Country'] != 'Antarctica']
df

Country              Total_area  \
1                                         Russia  17,098,246 (6,601,667)   
2                                         Canada   9,984,670 (3,855,100)   
3/4 [e]                                    China   9,596,960 (3,705,410)   
3/4 [e]                            United States   9,525,067 (3,677,647)   
5                                         Brazil   8,510,346 (3,285,862)   
...                                          ...                     ...   
NaN      Ashmore and Cartier Islands (Australia)               5.0 (1.9)   
NaN                Coral Sea Islands (Australia)               3.0 (1.2)   
NaN                   Spratly Islands (disputed)              2.0 (0.77)   
194                                       Monaco              2.0 (0.77)   
195                                 Vatican City             0.49 (0.19)   

                      Land_area         Water_area  Water_percentage  
1        16,376,870 (6,323,142)  721,380 (278,530)               4.2  
2         9,093,507 (3,511,021)  891,163 (344,080)               8.9  
3/4 [e]   9,326,410 (3,600,950)  270,550 (104,460)               2.8  
3/4 [e]   9,147,593 (3,531,904)  377,424 (145,724)               4.0  
5         8,460,415 (3,266,583)    55,352 (21,372)               0.6  
...                         ...                ...               ...  
NaN                   5.0 (1.9)                  0               0.0  
NaN                   3.0 (1.2)                  0               0.0  
NaN                  2.0 (0.77)                  0               0.0  
194                  2.0 (0.77)                  0               0.0  
195                 0.49 (0.19)                  0               0.0  

[262 rows x 5 columns]

In [126]:
df

Country              Total_area  \
1                                         Russia  17,098,246 (6,601,667)   
2                                         Canada   9,984,670 (3,855,100)   
3/4 [e]                                    China   9,596,960 (3,705,410)   
3/4 [e]                            United States   9,525,067 (3,677,647)   
5                                         Brazil   8,510,346 (3,285,862)   
...                                          ...                     ...   
NaN      Ashmore and Cartier Islands (Australia)               5.0 (1.9)   
NaN                Coral Sea Islands (Australia)               3.0 (1.2)   
NaN                   Spratly Islands (disputed)              2.0 (0.77)   
194                                       Monaco              2.0 (0.77)   
195                                 Vatican City             0.49 (0.19)   

                      Land_area         Water_area  Water_percentage  
1        16,376,870 (6,323,142)  721,380 (278,530)               4.2  
2         9,093,507 (3,511,021)  891,163 (344,080)               8.9  
3/4 [e]   9,326,410 (3,600,950)  270,550 (104,460)               2.8  
3/4 [e]   9,147,593 (3,531,904)  377,424 (145,724)               4.0  
5         8,460,415 (3,266,583)    55,352 (21,372)               0.6  
...                         ...                ...               ...  
NaN                   5.0 (1.9)                  0               0.0  
NaN                   3.0 (1.2)                  0               0.0  
NaN                  2.0 (0.77)                  0               0.0  
194                  2.0 (0.77)                  0               0.0  
195                 0.49 (0.19)                  0               0.0  

[262 rows x 5 columns]

In [130]:
# Convert the columns to string 
df['Total_area'] = df['Total_area'].astype(str)
df['Land_area'] = df['Land_area'].astype(str)
df['Water_area'] = df['Water_area'].astype(str)

# Remove the values in parentheses for each relevant column using regex
df['Total_area'] = df['Total_area'].str.replace(r'\(.*\)', '', regex=True).str.replace(',', '')
df['Land_area'] = df['Land_area'].str.replace(r'\(.*\)', '', regex=True).str.replace(',', '')
df['Water_area'] = df['Water_area'].str.replace(r'\(.*\)', '', regex=True).str.replace(',', '')

# Convert columns back to numeric
df['Total_area'] = pd.to_numeric(df['Total_area'], errors='coerce')
df['Land_area'] = pd.to_numeric(df['Land_area'], errors='coerce')
df['Water_area'] = pd.to_numeric(df['Water_area'], errors='coerce')

df

Country   Total_area    Land_area  \
1                                         Russia  17098246.00  16376870.00   
2                                         Canada   9984670.00   9093507.00   
3/4 [e]                                    China   9596960.00   9326410.00   
3/4 [e]                            United States   9525067.00   9147593.00   
5                                         Brazil   8510346.00   8460415.00   
...                                          ...          ...          ...   
NaN      Ashmore and Cartier Islands (Australia)         5.00         5.00   
NaN                Coral Sea Islands (Australia)         3.00         3.00   
NaN                   Spratly Islands (disputed)         2.00         2.00   
194                                       Monaco         2.00         2.00   
195                                 Vatican City         0.49         0.49   

         Water_area  Water_percentage  
1          721380.0               4.2  
2          891163.0               8.9  
3/4 [e]    270550.0               2.8  
3/4 [e]    377424.0               4.0  
5           55352.0               0.6  
...             ...               ...  
NaN             0.0               0.0  
NaN             0.0               0.0  
NaN             0.0               0.0  
194             0.0               0.0  
195             0.0               0.0  

[262 rows x 5 columns]

In [132]:
# reset the index
df.reset_index(drop=True, inplace=True)
df

Country   Total_area    Land_area  \
0                                     Russia  17098246.00  16376870.00   
1                                     Canada   9984670.00   9093507.00   
2                                      China   9596960.00   9326410.00   
3                              United States   9525067.00   9147593.00   
4                                     Brazil   8510346.00   8460415.00   
..                                       ...          ...          ...   
257  Ashmore and Cartier Islands (Australia)         5.00         5.00   
258            Coral Sea Islands (Australia)         3.00         3.00   
259               Spratly Islands (disputed)         2.00         2.00   
260                                   Monaco         2.00         2.00   
261                             Vatican City         0.49         0.49   

     Water_area  Water_percentage  
0      721380.0               4.2  
1      891163.0               8.9  
2      270550.0               2.8  
3      377424.0               4.0  
4       55352.0               0.6  
..          ...               ...  
257         0.0               0.0  
258         0.0               0.0  
259         0.0               0.0  
260         0.0               0.0  
261         0.0               0.0  

[262 rows x 5 columns]

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Country           262 non-null    object 
 1   Total_area        262 non-null    float64
 2   Land_area         253 non-null    float64
 3   Water_area        253 non-null    float64
 4   Water_percentage  253 non-null    float64
dtypes: float64(4), object(1)
memory usage: 10.4+ KB


In [134]:
df.describe()

Total_area     Land_area     Water_area  Water_percentage
count  2.620000e+02  2.530000e+02     253.000000        253.000000
mean   5.323232e+05  5.311727e+05   16753.924901          2.499209
std    1.677945e+06  1.639126e+06   80708.866464          5.589382
min    4.900000e-01  4.900000e-01       0.000000          0.000000
25%    7.862500e+02  8.110000e+02       0.000000          0.000000
50%    5.390150e+04  6.186000e+04     440.000000          0.700000
75%    3.536858e+05  3.644850e+05    6080.000000          2.600000
max    1.709825e+07  1.637687e+07  891163.000000         66.700000