In [18]:
names = ["Sam", "Obed", "Steve", "Kiarie", "Martha"]

for name in names:
    print(f"Hello  {name}, we are happy to have you!")

Hello  Sam, we are happy to have you!
Hello  Obed, we are happy to have you!
Hello  Steve, we are happy to have you!
Hello  Kiarie, we are happy to have you!
Hello  Martha, we are happy to have you!


### Lists

In [19]:
new_list = []
names = list()
print(names)
names.append("Sam")
print(names)

[]
['Sam']


In [20]:
colors = ["red", "blue", "green", "yellow"]
print("White" in colors)
print("red" in colors)
colors.insert(2, "purple")
print(colors)

False
True
['red', 'blue', 'purple', 'green', 'yellow']


In [21]:
for color in colors:
    print(color)

red
blue
purple
green
yellow


In [22]:
print(colors[:1])

['red']


In [23]:
# Creating a tuple
fruits = ("apple", "banana", "cherry")
print(fruits)  # Output: ('apple', 'banana', 'cherry')

# Accessing an item by index
print(fruits[1])  # Output: 'banana'

# Tuples are immutable, so you cannot add or remove items
# fruits.append("orange")  # This will raise an AttributeError

('apple', 'banana', 'cherry')
banana


In [24]:
# Creating a list
fruits = ["apple", "banana", "cherry"]
print(fruits)  # Output: ['apple', 'banana', 'cherry']

# Adding an item to the list
fruits.append("orange")
print(fruits)  # Output: ['apple', 'banana', 'cherry', 'orange']

# Accessing an item by index
print(fruits[1])  # Output: 'banana'

# Removing an item from the list
fruits.remove("banana")
print(fruits)  # Output: ['apple', 'cherry', 'orange']



['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry', 'orange']
banana
['apple', 'cherry', 'orange']


In [25]:
# Creating a dictionary
fruit_colors = {"apple": "red", "banana": "yellow", "cherry": "red"}
print(fruit_colors)  # Output: {'apple': 'red', 'banana': 'yellow', 'cherry': 'red'}

# Accessing a value by key
print(fruit_colors["banana"])  # Output: 'yellow'

# Adding a new key-value pair
fruit_colors["orange"] = "orange"
print(fruit_colors)  # Output: {'apple': 'red', 'banana': 'yellow', 'cherry': 'red', 'orange': 'orange'}

# Removing a key-value pair
del fruit_colors["banana"]
print(fruit_colors)  # Output: {'apple': 'red', 'cherry': 'red', 'orange': 'orange'}

{'apple': 'red', 'banana': 'yellow', 'cherry': 'red'}
yellow
{'apple': 'red', 'banana': 'yellow', 'cherry': 'red', 'orange': 'orange'}
{'apple': 'red', 'cherry': 'red', 'orange': 'orange'}


In [26]:
# String concatenation
greeting = "Hello"
name = "Alice"
message = greeting + " " + name
print(message)  # Output: Hello Alice

# String formatting using f-strings
age = 30
formatted_message = f"{name} is {age} years old."
print(formatted_message)  # Output: Alice is 30 years old.

# String slicing
substring = message[0:5]
print(substring)  # Output: Hello

# String methods
upper_case_message = message.upper()
print(upper_case_message)  # Output: HELLO ALICE

lower_case_message = message.lower()
print(lower_case_message)  # Output: hello alice

# Checking if a substring is in a string
contains_hello = "Hello" in message
print(contains_hello)  # Output: True

# Replacing a substring
new_message = message.replace("Alice", "Bob")
print(new_message)  # Output: Hello Bob

Hello Alice
Alice is 30 years old.
Hello
HELLO ALICE
hello alice
True
Hello Bob


### Sets, Tuples and Lists
* Lists -> ordered mutable collection of items. Ex. marks = [1,2,2,3,4]
* Tuple -> ordered immutable collection of items. Ex. marks =(1,2,2,3,4)
* Sets -> Unordered mutable collection of unique items. Ex. marks = {1,2,3,4}

In [27]:
# List example
my_list = [1, 2, 3, 4, 5]
print("List:", my_list)  # Output: List: [1, 2, 3, 4, 5]

# Lists are mutable, meaning you can change their content
my_list.append(6)
print("List after append:", my_list)  # Output: List after append: [1, 2, 3, 4, 5, 6]

# Tuple example
my_tuple = (1, 2, 3, 4, 5)
print("Tuple:", my_tuple)  # Output: Tuple: (1, 2, 3, 4, 5)

# Tuples are immutable, meaning you cannot change their content
# my_tuple.append(6)  # This will raise an AttributeError

# Set example
my_set = {1, 2, 3, 4, 5}
print("Set:", my_set)  # Output: Set: {1, 2, 3, 4, 5}

# Sets are mutable, but they do not allow duplicate elements
my_set.add(6)
print("Set after add:", my_set)  # Output: Set after add: {1, 2, 3, 4, 5, 6}
my_set.add(3)  # Adding a duplicate element has no effect
print("Set after adding duplicate:", my_set)  # Output: Set after adding duplicate: {1, 2, 3, 4, 5, 6}

List: [1, 2, 3, 4, 5]
List after append: [1, 2, 3, 4, 5, 6]
Tuple: (1, 2, 3, 4, 5)
Set: {1, 2, 3, 4, 5}
Set after add: {1, 2, 3, 4, 5, 6}
Set after adding duplicate: {1, 2, 3, 4, 5, 6}


### Anonymous lamda

In [28]:
# function without a name
multiply = lambda x, y: x * y
print(multiply(4, 5))

sum = lambda x, y: x + y
print(sum(4, 5))

remainder = lambda x, y: x % y
print(remainder(23, 5))

20
9
3


In [29]:
def test(n):
    return lambda x: x * n

test_1 = test(18797)
print(test_1(108239))

2034568483


In [30]:
message = "DeepSeek is taking on OpenAI"
for item in message:
    if item == "X":
        break

else: 
    print("There is no 'X' in the message")

There is no 'X' in the message


In [31]:
# password checking program
attempts = 0
while attempts < 3:
    password = input("Enter your password: ")
    if password == "password":
        print("Access granted")
        break
    else:
        print("Access denied")
        attempts += 1
if attempts == 3:
    print("Access denied. You have exceeded the maximum number of attempts")

Access granted


In [32]:
class Car:
    color = "red"
    make = "Toyota"
    model = "Corolla"
model_1 = Car()
print(model_1.color, model_1.make, model_1.model)



red Toyota Corolla


#### Class

In [33]:
class Vehicle:
    def __init__(self, color, make, model):
        self.color = color
        self.make = make
        self.model = model

    def display_vehicle(self):
        print(f"Color: {self.color}")
        print(f"Make: {self.make}")
        print(f"Model: {self.model}")
    
    def change_color(self, new_color):
        self.color = new_color
    
    @staticmethod
    def honk():
        print("Beep beep")
    
    @classmethod
    def get_vehicle(cls):
        return cls("red", "Toyota", "Corolla")

vehicle_1 = Vehicle("red", "Toyota", "Corolla")
vehicle_1.display_vehicle()

vehicle_1.change_color("blue")
vehicle_1.display_vehicle()

Vehicle.honk() # Output: Beep beep
vehicle_2 = Vehicle.get_vehicle()

vehicle_2.display_vehicle()
vehicle_2.get_vehicle()

del vehicle_2 


Color: red
Make: Toyota
Model: Corolla
Color: blue
Make: Toyota
Model: Corolla
Beep beep
Color: red
Make: Toyota
Model: Corolla


### Inheritance

In [34]:
class Animal:
    def __init__(self, species, sound):
        self.species = species
        self.sound = sound

    def make_sound(self):
        print(self.sound)

    def display_species(self):
        print(self.species)

mammmal = Animal("Mammal", "Roar")
mammmal.display_species()
mammmal.make_sound()

class Dog(Animal):
    def __init__(self, species, sound, breed):
        super().__init__(species, sound) # Call the __init__ method of the parent class
        self.breed = breed

    def display_breed(self):
        print(self.breed)

dog = Dog("Mammal", "Bark", "Bulldog")
dog.display_species()
dog.make_sound()
dog.display_breed()

Mammal
Roar
Mammal
Bark
Bulldog


### List comprehension

In [35]:
# [expression for item in iterable if condition]
[print(i) for i in range(10) if i % 2 == 0]

0
2
4
6
8


[None, None, None, None, None]

In [36]:
# Set comprehension
set_comprehension = {x**2 for x in range(10)}
print("Set comprehension:", set_comprehension)

# Tuple comprehension (Note: There is no direct tuple comprehension, but you can use a generator expression and convert it to a tuple)
tuple_comprehension = tuple(x**2 for x in range(10))
print("Tuple comprehension:", tuple_comprehension)

Set comprehension: {0, 1, 64, 4, 36, 9, 16, 49, 81, 25}
Tuple comprehension: (0, 1, 4, 9, 16, 25, 36, 49, 64, 81)


In [37]:
# Dictionary comprehension
squares = {x: x**2 for x in range(10)}
print("Dictionary comprehension:", squares)

Dictionary comprehension: {0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


### Built-in modules in Python

In [67]:
import sys

# List all built-in modules
builtin_modules = sys.builtin_module_names
print(builtin_modules)
help('modules')

('_abc', '_ast', '_bisect', '_blake2', '_codecs', '_collections', '_csv', '_datetime', '_elementtree', '_functools', '_heapq', '_imp', '_io', '_locale', '_md5', '_operator', '_pickle', '_posixsubprocess', '_random', '_sha1', '_sha256', '_sha3', '_sha512', '_signal', '_socket', '_sre', '_stat', '_statistics', '_string', '_struct', '_symtable', '_thread', '_tracemalloc', '_warnings', '_weakref', 'array', 'atexit', 'binascii', 'builtins', 'cmath', 'errno', 'faulthandler', 'fcntl', 'gc', 'grp', 'itertools', 'marshal', 'math', 'posix', 'pwd', 'pyexpat', 'select', 'spwd', 'sys', 'syslog', 'time', 'unicodedata', 'xxsubtype', 'zlib')

Please wait a moment while I gather a list of all available modules...



/usr/lib/python3.8/pkgutil.py:92: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(info.name)


IPython             argparse            imghdr              retrying
PIL                 array               imp                 rlcompleter
__future__          ast                 importlib           runpy
_abc                asttokens           importlib_metadata  sched
_ast                asynchat            importlib_resources scipy
_asyncio            asyncio             inspect             seaborn
_bisect             asyncore            io                  secrets
_blake2             atexit              ipaddress           select
_bootlocale         audioop             ipykernel           selectors
_bz2                backcall            ipykernel_launcher  setuptools
_codecs             base64              itertools           shelve
_codecs_cn          bdb                 jedi                shlex
_codecs_hk          binascii            joblib              shutil
_codecs_iso2022     binhex              json                signal
_codecs_jp          bisect              jupyter   

In [48]:
import random #Altanatively: from random import randint, random, choice, shuffle

# Generate a random integer between 1 and 10
random_int = random.randint(4, 9000000)
print(f"Random integer between 1 and 9000000: {random_int}")

# Generate a random float between 0 and 1
random_float = random.random()
print(f"Random float between 0 and 1: {random_float}")

# Choose a random element from a list
colors = ["red", "blue", "green", "yellow","grey", "black" ]
random_color = random.choice(colors)
print(f"Random color: {random_color}")

# Shuffle a list
random.shuffle(colors)
print(f"Shuffled colors: {colors}")

print("Done!")

Random integer between 1 and 9000000: 3214215
Random float between 0 and 1: 0.9800258271176722
Random color: blue
Shuffled colors: ['blue', 'black', 'yellow', 'red', 'grey', 'green']
Done!


#### Math module

In [58]:
import math

math.sqrt(16) # Output: 4.0
print(math.e)
print(math.pi)
print(math.degrees(math.pi))
print(math.radians(180))
math.sin(83.2)
math.acos(0.5)

2.718281828459045
3.141592653589793
180.0
3.141592653589793


1.0471975511965979

In [59]:
import math

angle = 0.5  # Example angle in radians
inverse_cosine = math.acos(angle)
print(f"The inverse cosine (arccos) of {angle} is {inverse_cosine} radians")

The inverse cosine (arccos) of 0.5 is 1.0471975511965979 radians


In [65]:
import statistics
statistics.mean([1, 2, 3, 4, 4])  # Output: 2.8
statistics.median([1, 2, 3, 4, 4])  # Output: 3
statistics.NormalDist(mu=0, sigma=1).pdf(0)  # Output: 0.3989422804014327
statistics.mode([1, 2, 3, 4, 4])  # Output: 4
statistics.stdev([1, 2, 3, 4, 4])  # Output: 1.3038404810405297

1.3038404810405297

In [66]:
# In Python, there are several types of errors that you might encounter. Here are some common ones:

# 1. **SyntaxError**: This occurs when the code is not written in proper Python syntax.
if True:
    print("Hello")  # Missing colon (:) after the if statement

# 2. **IndentationError**: This occurs when the code is not properly indented.
def my_function():
    print("Hello")  # This line should be indented

# 3. **NameError**: This occurs when a variable or function name is not found.
print(x)  # x is not defined

# 4. **TypeError**: This occurs when an operation or function is applied to an object of inappropriate type.
print("Hello" + 5)  # Cannot concatenate a string and an integer

# 5. **ValueError**: This occurs when a function receives an argument of the right type but inappropriate value.
int("Hello")  # Cannot convert a string that is not a number to an integer

# 6. **IndexError**: This occurs when trying to access an element from a list using an index that is out of range.
my_list = [1, 2, 3]
print(my_list[5])  # Index 5 is out of range

# 7. **KeyError**: This occurs when trying to access a dictionary with a key that does not exist.
my_dict = {"a": 1, "b": 2}
print(my_dict["c"])  # Key 'c' does not exist

# 8. **AttributeError**: This occurs when trying to access an attribute that does not exist for an object.
my_list = [1, 2, 3]
my_list.append(4)
my_list.push(5)  # 'list' object has no attribute 'push'

# 9. **ImportError**: This occurs when an import statement fails to find the module definition or when a from ... import fails to find a name that is to be imported.
import non_existent_module  # No module named 'non_existent_module'

# 10. **ZeroDivisionError**: This occurs when a division or modulo operation is performed with zero as the divisor.
print(10 / 0)  # Division by zero

# These are just a few examples of common errors in Python. Understanding these errors can help you debug your code more effectively.

SyntaxError: invalid syntax (1236417019.py, line 1)

In [ ]:
try:
    # Code that may raise an exception
    result = 10 / 0
except ZeroDivisionError as e:
    # Code to handle the exception
    print(f"Error: {e}")
else:
    # Code to execute if no exception is raised
    print("No exceptions were raised.")
finally:
    # Code to execute regardless of whether an exception was raised or not
    print("This block is always executed.")

# Example with multiple exceptions
try:
    value = int("Hello")
except ValueError as e:
    print(f"ValueError: {e}")
except TypeError as e:
    print(f"TypeError: {e}")

In [72]:
import io

new_text = "Learning Python is fun!"
with open("example.txt", "w") as file:
    file.write(new_text)
    
with open("example.txt", "r") as file:
    content = file.read()
    print(content)

with open("example.txt", "a") as file:
    file.write("\nI love Python!")

# Move the cursor to the beginning of the file
# file.seek(0)

# Reopen the file in read mode and read the updated content
with open("example.txt", "r") as file:
    updated_content = file.read()
    print(updated_content)

Learning Python is fun!
Learning Python is fun!
I love Python!


In [73]:
import os

# Get the current working directory
current_directory = os.getcwd()
print(f"Current Directory: {current_directory}")

# List all files and directories in the current directory
files_and_directories = os.listdir(current_directory)
print(f"Files and Directories: {files_and_directories}")

# Create a new directory
new_directory = "new_folder"
os.makedirs(new_directory, exist_ok=True)
print(f"Created new directory: {new_directory}")

# Rename a directory
renamed_directory = "renamed_folder"
os.rename(new_directory, renamed_directory)
print(f"Renamed directory to: {renamed_directory}")

# Remove a directory
os.rmdir(renamed_directory)
print(f"Removed directory: {renamed_directory}")

# Get the value of an environment variable
home_directory = os.getenv("HOME")
print(f"Home Directory: {home_directory}")

# Set an environment variable
os.environ["MY_VARIABLE"] = "my_value"
print(f"MY_VARIABLE: {os.getenv('MY_VARIABLE')}")

Current Directory: /home/wanyua/Dev/ML/Python-Machine-Learning-Tutorial/Python
Files and Directories: ['example.txt', 'python_basics.ipynb', 'app.py']
Created new directory: new_folder
Renamed directory to: renamed_folder
Removed directory: renamed_folder
Home Directory: /home/wanyua
MY_VARIABLE: my_value


In [74]:
import shutil

# Copy a file
shutil.copy("example.txt", "example_copy.txt")
print("File copied successfully.")

# Move a file
shutil.move("example_copy.txt", "example_moved.txt")
print("File moved successfully.")

# Remove a file
os.remove("example_moved.txt")
print("File removed successfully.")

File copied successfully.
File moved successfully.
File removed successfully.


In [75]:
import copy

# Original list
original_list = [1, 2, [3, 4], 5]

# Shallow copy - modifications in the copied object can affect the original if it contains mutable objects.

shallow_copy = copy.copy(original_list)

# Deep copy - Changes in the copied object do not affect the original.

deep_copy = copy.deepcopy(original_list)

# Modify the original list
original_list[2][0] = 'Changed'

print("Original list:", original_list)  # Output: [1, 2, ['Changed', 4], 5]
print("Shallow copy:", shallow_copy)    # Output: [1, 2, ['Changed', 4], 5]
print("Deep copy:", deep_copy)          # Output: [1, 2, [3, 4], 5]

Original list: [1, 2, ['Changed', 4], 5]
Shallow copy: [1, 2, ['Changed', 4], 5]
Deep copy: [1, 2, [3, 4], 5]


In [ ]:
# !pip install send2trash
import send2trash

# Send a file to the trash
send2trash.send2trash("example.txt")
print("File sent to trash successfully.")

# Send a directory to the trash
send2trash.send2trash("new_folder")
print("Directory sent to trash successfully.")

In [77]:
import zipfile
import os

new_file = open('example_moved.txt', 'w')
# Create a zip file
with zipfile.ZipFile('example.zip', 'w') as zipf:
    zipf.write('example.txt')
    zipf.write('example_moved.txt')

print("Files zipped successfully.")

# Unzip the file
with zipfile.ZipFile('example.zip', 'r') as zipf:
    zipf.extractall('extracted_files')

print("Files unzipped successfully.")

# List the contents of the extracted directory
extracted_files = os.listdir('extracted_files')
print(f"Extracted files: {extracted_files}")

Files zipped successfully.
Files unzipped successfully.
Extracted files: ['example.txt', 'example_moved.txt']


In [81]:
import numpy as np

# Create a NumPy array from a list
array_from_list = np.array([1, 2, 3, 4, 5])
print("Array from list:", array_from_list)

# Create a NumPy array with a range of values
array_range = np.arange(9)
print("Array with range of values:", array_range)

# Create a NumPy array with zeros
array_zeros = np.zeros((3, 3))
print("Array with zeros:\n", array_zeros)

# Create a NumPy array with ones
array_ones = np.ones((2, 4))
print("Array with ones:\n", array_ones)

# Create a NumPy array with random values
array_random = np.random.random((4, 4))
print("Array with random values:\n", array_random)

# Perform basic arithmetic operations on NumPy arrays
array_sum = array_from_list + 10
print("Array after addition:", array_sum)

array_product = array_from_list * 2
print("Array after multiplication:", array_product)

# Access elements of a NumPy array
element = array_from_list[2]
print("Element at index 2:", element)

# Slicing a NumPy array
array_slice = array_from_list[1:4]
print("Sliced array:", array_slice)

Array from list: [1 2 3 4 5]
Array with range of values: [0 1 2 3 4 5 6 7 8]
Array with zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array with ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array with random values:
 [[0.45037838 0.04657062 0.21650479 0.62893839]
 [0.45737238 0.37754599 0.12188324 0.77510976]
 [0.69889786 0.23656815 0.6579891  0.90588845]
 [0.81050128 0.81018526 0.65894468 0.48645593]]
Array after addition: [11 12 13 14 15]
Array after multiplication: [ 2  4  6  8 10]
Element at index 2: 3
Sliced array: [2 3 4]


In [84]:
marks = [12.1, 13.2, 14.3, 15.4, 16.5]
np_marks = np.array(marks)
double_marks = np_marks * 2
print(f"Double marks: {double_marks}")

Double marks: [24.2 26.4 28.6 30.8 33. ]
